### ISSUE TITLE
Default Roll Template available in all games Not Compatible with Dark Mode

### ISSUE THREAD

**Issue by veratulmp** [Roll20/roll20-character-sheets#10474]
The default roll template &{template:default} is not readable in dark mode.
![image](https://user-images.githubusercontent.com/60524628/163053742-e2b06073-1e81-4253-9621-9fb86dded766.png)
![image](https://user-images.githubusercontent.com/60524628/163053797-39859bdd-08b8-405d-b40d-206ef869868e.png)

**Comment by Anduh** [comment]
1. **Does this still happen?** To me this seems fixed.
![darkmode-def-rollltemplate](https://user-images.githubusercontent.com/2890634/164893376-ed1e4624-ac3d-45d0-92f5-689d328c7baa.png)

2. **Can you provide the macro you used in these examples?** If those macros/rolls are from a character sheet template, tell us which sheet template it was, and button you pressed to get these.

Please close this issue as resolved, if the problem is gone.

**Comment by veratulmp** [comment]
@Anduh, I did some more testing and my findings have narrowed down the problem.

The default template is readable if you are in dark mode when you make the roll. However, if you then switch to light mode and then back to dark, or make the roll first in light mode then switch to dark mode, the text does not update to the white color.

Give that a try and see if you get the same result.

**Comment by Anduh** [comment]
It's best you report this on https://app.roll20.net/forum/post/10728562/dark-mode-vtt-bug-thread, the github issues here are for reporting issues with individual community/publisher-made sheets, not for general Roll20 bugs or related to "by Roll20"-sheets(as they aren't on github anyway).

**Comment by veratulmp** [comment]
Good point, @Anduh. I'll close this issue here. Thanks for your help.
