### ISSUE TITLE
CSS broken for all of Ada Lindberg's character sheets

### ISSUE THREAD

**Issue by Cazra** [Roll20/roll20-character-sheets#10699]
I recently updated the `sheet.json` files for all the character sheets I've made to fix my deadname (changing it from "Stephen Lindberg" to "Ada Lindberg"). This seems to have had the disastrous effect of making it so that Roll20 no longer loads the CSS for my sheets properly. I don't think this is an issue I can fix myself (unless I revert all my sheets back to use my deadname, which I'd much rather not do).

**Comment by Cazra** [comment]
Someone recommended that I should add the field `"legacy": true` to my sheet.json files. It's been a while since I've touched my character sheets, so I didn't know about this new field. I'll try adding it to see if it fixes the issue.

**Comment by Anduh** [comment]
Back when [Character Sheet Enhancement](https://wiki.roll20.net/CSE) was released for Roll20, they went and updated the `sheet.json` for all existing sheet to include `"legacy": true`, but seems they missed some.

I suspect it had been fine until now bc the sheet.json hadn't been edited since, and the update you made resulted in Roll20's system reloading it fully, and seems that if `legacy` isn't defined, it will default to `"legacy": false` i.e that the updated sheet versions are used.
