### ISSUE TITLE
RMSS Sheet reads "+2" as string

### ISSUE THREAD

**Issue by Skippern** [Roll20/roll20-character-sheets#1239]
The RMSS Sheet, on many different cells reads "+2" as string, while other cells reads the same "+2" as a number. This results in sometimes +2 not being calculated. I need to constantly monitor changes on character sheets in my group to see when +2 is handled as string and when as number so the sheet is calculated correctly.

I have forked the sheets, but cannot figure out what in the HTML sheet that goes wrong.

If I get pointed in the right direction I can look up and fix what it is and make a PR

**Comment by suldae** [comment]
Please just use a 2 instead of a +2.  The reason the +2 is sometimes not calculated is that it gets resolved in Roll20 as a ++2 which is not a mathematical operation which the system understands.  I actually don't know what is different when it does work correctly, but the sheet assumes you will put in a 2 (or a -2 if there is a penalty; that does work).
