### ISSUE TITLE
[Starfinder By Roll20] Translations haven't been updated since 5 years

### ISSUE THREAD

**Issue by Baleine82** [Roll20/roll20-character-sheets#13438]
Translations for the game "Starfinder by Roll20" are very much out of date.
The last update to these translations has been done 5 years ago (https://github.com/Roll20/roll20-character-sheets/tree/master/Starfinder%20by%20Roll20/translations), but it seems like the newest changes made in crowdin haven't be merged.

It's quite annoying, since the current french translation for "aft" is the french word for "starboard", and the translation for "starboard" is the french word for "aft". (see https://roll20.crowdin.com/editor/40/5084/en-fr/346?view=comfortable&filter=basic&value=0&em#q=starboard)

I checked on crowdin, and it has been changed 2 years ago.

Could you please retrieve the latest translations?

**Comment by BronsonHall** [comment]
Hey @Baleine82 

As Nora noted on your PR for this sheet, the Starfinder by Roll20 sheet was transferred to our private repo for Roll20 official sheets  some time ago.  The code and translations in this folder are no longer live, and are just left up on the public repo for reference. 

I'm seeing that crowdin translations are going through, and getting updated in the live folder as expected.  That said, if you're noticing that the translations are incorrect on the sheet in-game on Roll20, please let us know!  That could be an issue on our end. 

Thanks!

**Comment by Baleine82** [comment]
All right. Well I hope you’ll update the translations soon then, because, it’s really confusing when your starboard is your aft and your aft is your starboard.

**Comment by BronsonHall** [comment]
Hey @Baleine82 

To clarify, this is already updated and correct on the sheet in-game.  `"starboard": "TRIBORD"` is the translation in our live version of the sheet code, which does match crowdin.  I'm also seeing the correct translations used in-game.

The code you see in this repo is not the real sheet's code, just an archived, outdated version of it we've left available to help sheet authors who are learning to create sheets.   

It thus does not receive any updates from crowdin - those go directly to our private repo's version of the sheet, which is the one you actually see in a Starfinder game on the site. 

If you spot a problem with the Starfinder sheet on roll20, please do report it to us either on the forums or in a help desk ticket!  But if there's an issue in the code in this repo that isn't replicable in the live sheet, that generally means it was spotted and fixed in the actual sheet code on our private repo.  This is the case for all the "by Roll20" sheets on this repo.

**Comment by Baleine82** [comment]
Oh… Damn, I hope I didn't load the sheet from the repository to check that out.

Well, The good thing is that it's correct on the production version. Thank you for the clarification and sorry if I wasted your time.
I didn't knew these sheets where handled on this particular manner 😞

**Comment by BronsonHall** [comment]
Oh, no worries - we definitely don't do enough to make that pattern clear on this repo.  I'll look into a way we can better present those folders as archived.  Some of those sheets have transformed so significantly that trying to compare the old code and the sheet on production would just cause confusion.
