### ISSUE TITLE
[D&D 3.5] Unable to call spells levels in section 1 column 1

### ISSUE THREAD

**Issue by dani-arde** [Roll20/roll20-character-sheets#2041]
Hello.
When I need to call the level number of a specific spell, I usually write in a macro or in the chat input area @{character_name|repeating_spellsXY_$ZZ_spelllevelXY}, where X defines the "Spell Section" number, Y the subsection column (1 or 2) and ZZ is the row of the spell.

This works just fine, except for spells in section 1 column 1.
I think the issue is that every filed in that section is titled "repeating_spells_#_"  instead of "repeating_spells11_#_".

Thanks in advance for your help and your work.

**Comment by suldae** [comment]
That section is titled with repeating_spells_# because that is in fact its name.  That section was the first one I built and when I put the naming convention in for the rest of the spells, I did not remember to update that one.  Thus, to access that area you will need to use, for example, @{selected|repeating_spells_$0_spellname11} .

I understand it doesn't follow the convention used on the rest of the sections, but I don't plan on changing it to match at this point in time because it would remove/delete the information that people have entered into that area on their character sheets and I would rather not discard their work.  (It would also invalidate macros that currently exist that reference that section).

Sorry for the hassle.

**Comment by dani-arde** [comment]
Hello and thanks for your reply.
I understand why you won't change the naming, I would lose my mind too if my macros got deleted. However if you try to call spell attributes with @{selected|repeating_spells_$X_spellname11}, you will always get "Doom" for spellname, and "1" for spelllevel.
No matter what you put in every row, you will always get the information of the default Doom spell.
Is there any workaround for this?

**Comment by suldae** [comment]
I am afraid that I don't see that behavior.  

That section acts the same as any other section for me.  For example, on my druid, @{selected|repeating_spells_$0_spellname11} gives me Beast Claws, @{selected|repeating_spells_$1_spellname11} gives me Beget Bogun, and @{selected|repeating_spells_$2_spellname11} gives me Calm Animals which are the spells in rows 1, 2, and 3 for that section.  I get 1 for the spell level for all those but that is because those are all level 1 spells for my druid.

Have you tried with more than one character?  Or possibly copy the campaign and try in the copy to rule out something odd going on?  

If you would like to send me an invite to your game, I can try poking at it and see if I can figure out what's up though no promises I can find anything (and I may need temporary GM status to do so).  I am https://app.roll20.net/users/108188/diana-p on Roll20.  Alternately,  if you wanted to look at my druid's setup, you can hop into my test campaign: https://app.roll20.net/join/796883/M9OjQA .  The druid is "Tathar".

**Comment by dani-arde** [comment]
Ok, this is so odd.
I followed your advices with the help of my GM and we found out that some characters in this campaign are able to call correctly the spellname and spelllevel attributes of section 11 while others, including me, can't. My GM made a copy of the campaign, but it happens the same thing.

I also found out that adding a new attribute, under the "Attributes&Abilities" tab, named "repeating_spells_$0_spelllevel11" or "repeating_spells_$0_spellnamel11" solves the problem.
Even stranger: after adding these new attributes, if you close and reopen the sheet they disappear from the list, but the workaround works all the same.

**Comment by suldae** [comment]
That is odd.  Very odd.  

Hopefully you won't need to remake your character to get it to work correctly (admittedly it's a bit faster having an existing sheet to copy from but still annoying.)

At this point in time, if this issue persists, you might want put in a bug report in the bug reports and technical issues forum ( https://app.roll20.net/forum/category/18 ) and see if they have any other ideas or can help.  You could add a link back to this issue thread in addition to the rest of the information they ask for.

They will ask that you follow these steps: 

> If you are experiencing technical issues with Roll20 being broken in a major way (e.g. nothing shows up on your maps), please follow these instructions: https://wiki.roll20.net/Solving_Technical_Issues
> 
> ---
> 
> Bug reports are a crucial part of the beta process. We want your help in making sure that everything works as it should across a wide variety of setups. If you've found something that doesn't seem quite right (or doesn't function as advertised), please let us know by submitting a new post in the Bug Reports forum. If possible, please follow this format:
> 
> Detailed Description of the Problem
> 
> Steps to Reproduce the Problem
> 
> Description of Your Setup (Browser + Version, Operating System, etc.) (A good place to get that info if you don't know it: http://supportdetails.com/)
> 
> You can also include screenshots by using the "Attach a File" link when submitting a post. The more information you can give us, the better able we'll be to fix the issue promptly!
> 
> Thanks!

Sorry I can't help further; I don't have any other ideas to try at this point in time.

Good luck!

**Comment by dani-arde** [comment]
Hello,

I solved the problem long ago with the workaround I described above and that campaign is currently on hiatus.
My character works fine now so I can't reproduce the bug itslef. Maybe it's possible to test it by creating a  brand new game and calling the spell attributes as we described above from a few character sheets.

Thank you for your interest in this matter.

**Comment by clevett** [comment]
I'm going to go ahead and make note of the work around here. I'll close this issue since it is a bit dated. If I see it comes up again we can try to look at it a bit closer. Thanks for the update.

-Cassie
