### ISSUE TITLE
[GURPS] Dodge being halved whilst Current FP is still over 1/3rd Maximum FP

### ISSUE THREAD

**Issue by calibraptor** [Roll20/roll20-character-sheets#2324]
https://i.gyazo.com/f291d85c95888a1b1a140a3eeeb541c5.png

9/10 FP is definitely over 1/3rd of the character's maximum FP.

**Comment by RhOmicron** [comment]
It seems strength and movement isnt halved either?

**Comment by calibraptor** [comment]
Yeah it's halving dodge once you go anywhere below maximum FP, but doesn't touch your ST or move no matter how low your FP is.

Calculations are pretty shagged here.

**Comment by sdJasper** [comment]
Working on this issue now. It seems the FP calculation was off. The HP is working, but another issue could be causing the script to see max HP as undefined. I've updated the initialization script that should now get good values into derivative stats.

I also was not reducing ST at all, so that's in now. Also the reduction should stack if a character has both low HP and FP.

**Comment by sdJasper** [comment]
This issue has been fixed, can this be closed?

**Comment by KlingonMike** [comment]
Yes it may be closed as the issue has been fixed for some time now.
