### ISSUE TITLE
Toolbar macros not working for Conan 2d20 sheet

### ISSUE THREAD

**Issue by jfsantos** [Roll20/roll20-character-sheets#2712]
When I drag and drop any of the skill roll buttons from a character sheet to the macro toolbar, the macro does not work. It always activates one of the talents of the character, instead of rolling the appropriate skill.

**Comment by Gussancho** [comment]
All the rolls have the same name... name='roll_skill' ... can it be because of this?

**Comment by suntzu777** [comment]
Gussancho , It would have been nice if you asked before modifying the sheet that I created , but since you went ahead and did the work I will forward all questions and queries in your direction

**Comment by Gussancho** [comment]
suntzu777, sorry if you felt offended because I solved a stupid roll problem without telling you after near three months with the bug open.
You don't have to worry, I will never touch the css nor the html, and probably I will never touch again "your" sheet. You're free to delete my changes.
Also, whoever you forward to me, I will be happy to help, but if I can't, I will happily forward them there to read this.
Have a happy day :3

**Comment by suntzu777** [comment]
What i was miffed about was that no one tried to contact me about the bug , the first i heard of this was when i received a notification of a fix being submitted for approval,  i don't mind you fixing the bug and will leave the fix in place , the original poster of this bug should have tried to contact on roll20 first

**Comment by clevett** [comment]
This appears to be solved so I'm going to go ahead and close the issue. If it needs to be opened again please let me know.

Thanks,
Cassie
