### ISSUE TITLE
[Dark Heresy 2nd Edition] Adding strength bonus twice when calculating melee damage

### ISSUE THREAD

**Issue by AgentA1cr** [Roll20/roll20-character-sheets#2845]
When rolling melee damage, the Dark Heresy 2nd Edition character sheet appears to be adding the Strength Bonus twice: once by referencing the Strength Bonus directly, and once by calculating it from the Strength stat.
For example, when rolling damage for an Omnissian Axe, which deals 2d10+4, wielded by a character with Strength 43 and Unnatural Strength 2, for a total strength bonus of 6, the resulting command is: /me does [[2d10+4+@{Aemilionus Dardashin|UnS}+(floor(@{Aemilionus Dardashin|strength}/10))]] Energy damage! (Pen: 6)
This results in a total of 2d10+4+6+(floor(43/10)), instead of the expected total of 2d10+4+6.

**Comment by AgentA1cr** [comment]
Just realized this is a duplicate of #2826, but I do feel mine gives more detail.

**Comment by AgentA1cr** [comment]
Also in what may be a related issue, the Agility bonus is added twice in much the same way when calculating initiative.

**Comment by Craftomega** [comment]
Is this on the advanced sheet or the regular sheet. 

Also are you placing your SRT and AGI bonus in the small box? Because that is for Unnatural Bonuses not regular.

Because I just tested it and your issue appears to not be occurring on the regular sheet.

**Comment by messiahcide** [comment]
Don't manually add the strength bonus in the profile ( the +4 at the beginning). You are inputing the sb when it's already calculated.

**Comment by NafenX** [comment]
I feel like this should be changed as it's still a problem today. Since I'm the only melee oriented character in my party we didn't realise it until just now when one of our members died and wrote up a new character.

Those little boxes in the corner of each Characteristic LOOK like they're supposed to be for putting in your Bonus for that stat so that's how we have been using them. Since I had Unnatural Strength and Toughness, it helped for me to see at a glance that I had 60 Strength and Toughness but my bonus for each of those stats was 7...but apparently each time I had hit a guy in melee it had been adding an extra 6 damage on top of the 7 from the Strength Bonus ..

**Comment by Craftomega** [comment]
@NafenX
In regards to your comment. The Unnatural box's have been there since the Deathwatch sheet was made many years ago. While occasionally people have the issue you are had, you are in the minority.

**Comment by clevett** [comment]
Hello,

I'm checking in on these older issues in GitHub to see if they are still unresolved. Can anyone provide me with an update on this issue? 

Thanks,
Cassie

**Comment by Craftomega** [comment]
It is resolved. It was user error.

**Comment by clevett** [comment]
Thanks for the update! I'll close this issue.
