### ISSUE TITLE
[5e OGL] The "model" character sheet promotes bad programming habits.

### ISSUE THREAD

**Issue by oukag** [Roll20/roll20-character-sheets#4401]
The 5e OGL is the main character sheet promoted for Roll20. It is also the character sheet pointed to when it comes to best utilizing Roll20's character sheet implementation (tabs, repeating sections, PC/NPC, charactermancer, etc.).

However this sheet seems poorly written in terms of structure or typical javascript best practices, for example:
 * extra semi-colons where not needed while some lines are missing recommended semi-colons
 * using ==/!= instead of ===/!==
 * not properly scoping variables (let is recommended in place of var for defining scoped variables)
 * unused variables

Most importantly, there are no comments whatsoever within the code. I don't see how this can be a teaching tool for other character sheets when there are no comments.

**Comment by clevett** [comment]
I agree. I will assure you that the 5e OGL sheet did not escape my gaze when we started the process of trying to implement best practices. :) Its been the best option we had to point people towards in the past and I hope to get a chance to do some refactoring to address these concerns yet with its size (over 16,000 lines) its not the best teaching tool. It has the advantage of when we release a new feature this sheet usually gets updated first so it can be an example to work from but this is a niche for the advanced sheet authors looking to utilize the latest updates. 

Can you recommend any sheets that promote good programming habits? I've reviewed over 500 sheets in our repository (just another 100 to go!) and made notes on all of them. I've been attempting to 'collect' the best examples to outline our standards & best practices. I'd appreciate a second opinion.

On the topic of teaching tool, there has been conversations about updating the 'kitchensink' to meet this goal. We have brain stormed adding a few of the common use features & tricks to it with a lot of commenting so new sheet authors would have a reference for doing tabs, drag/drop, roll templates...We could point towards 'live' sheets but they are subject to change and often contain styling beyond the strictly necessary in order to meet the needs of that game system or sheet style.

Any additional feedback you have would be most helpful. Input from active users such as yourself is invaluable to my task of curating the repository. :)

Thanks,
Cassie

**Comment by oukag** [comment]
The OGL sheet is the only sheet I use and have looked code. So I can't recommend other sheets for programming habits. However, I believe a development environment would show the plethora of warnings within the HTML of the sheet as well as the javascript warnings within the sheet workers/charactermancer sections.

**Comment by Anduh** [comment]
GUMESHOE Official at least was simle enough that I could steal the framework for a passable settings menu with some toggleable options(for the D6StarWars sheet). 
I cant't say much else, apart form the 5E OGL being too massive for me to have learned mostly anything from, when I was working on sheets.

**Comment by clevett** [comment]
Greetings friends,

I'm going to go ahead and close this post as its more of a commentary than a fixable issue. I can assure you its been read by my fellow devs and its in our minds of things to look at updating in the future (no ETA at this time). I'll put it on my list to consider changing the wiki examples to using the GUMSHOE or Dungeon World sheets as they are more digestible than the 5e one. 

Thanks again for the post. Dialogue like this one from our users help keep our priorities in scope.

- Cassie

**Comment by clevett** [comment]
Greetings  @oukag 

I wanted to let you know this quarter I have been actively working on this issue. Every week I've been adding PRs to refactor the 5e OGL code starting with the sheet workers. Hopefully we'll get the beast updated by the end of the year.

Best regards,
Cassie
