### ISSUE TITLE
[CWOD-V20] Attributes not counted in main dice pools

### ISSUE THREAD

**Issue by anborgi** [Roll20/roll20-character-sheets#4565]
when creating and rolling a main dice pool, the attribute it´s not accounted in the roll. 

![image](https://user-images.githubusercontent.com/12172371/50708693-858f1980-1065-11e9-9322-367c94e75dc5.png)

**Comment by agnelmeme** [comment]
There is a workaround I have found on current sheet for my players : adding StrengthScript, DexterityScript, StaminaScript, etc. instead of normal name for all attributes.
All attributes are named \@AttibuteScript while the only placeholders created on the character Attributes and Abilities tab are named without the Script suffix

**Comment by antonio-borderia** [comment]
Thanks for the idea. The creator of the sheet just pulled a fix to the dice and other bug issues. Hopefully it will be live soon to test.

**Comment by Anduh** [comment]
I guess this is solved then?

**Comment by RinVindor** [comment]
Yes this issue has been fixed and I've expanded the feature to include the boosted dice being listed adjacent to the normal attribute rating (1+0). I'm still absolutely taking more feedback for further improvements.

**Comment by nmbradley** [comment]
This appears to be resolved. Closing.
