### ISSUE TITLE
[Eclipse Phase Alternate] Ranged Defense Roll

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#4625]
Hi @Bathtor 

I've seen the Range Defense Roll it's not working right. It makes REF/2 instead Fray/2. I don't know if it's something of the translation or the sheet itself.

**Comment by Bathtor** [comment]
Oh, yeah...it's both actually.
- The sheet uses REF/2 instead of Fray/2 when it can't find the Fray skill in the skill list, assuming you have 0 points in it, and thus falling back to REF.
- If you are using skill translation it won't find the Fray skill in the list, because it's going to be named something else

Quick workaround: De-localise the Fray skill.
Fix: I've got to change the sheet worker to look for the localised version of Fray instead of "Fray".

I'm extremely busy irl right now, so I can't promise when it will be done :(

**Comment by clevett** [comment]
I'm going to close this issue as it looks like a pull request was put in to fix it. If its still an issue we can open it again. :)
