### ISSUE TITLE
[Black_Crusade] Multiple issues with the latest update

### ISSUE THREAD

**Issue by KriosMerew** [Roll20/roll20-character-sheets#4908]
The update that was committed in the last few days has created a few small issues that make it inconvenient to use. Here is a list of issues that need to be addressed.

- The Dodge skill doesn't work. A blank message is sent in the chat but doesn't provide the expected output.
- The NPC tab has a major UI issue. It appears as if the armour & defence table has been crushed together and is spaced weirdly. 
- The degrees of fail/success is calculating incorrectly. Success and Failure is not consistent in how it displays the initial degree. 
Example 1: The player has a skill of 30 and rolls a 59. The result is:
Degres of Fail : -1-3. 
However, it should be displaying (1 initial + 2 for the 20 that failed. Had it been a roll of 60 it would have been 4 degrees of failure)
Example 2: The player has a skill of 50 and rolls a 40. The result is:
Degres of Succes : 1+1 degrees. 
(This calculation is correct.)
- Spelling mistake when rolling a success."Degres of Succes :" should be "Degrees of Success:".
- Spelling mistake when rolling a failure. "Degres of Fail :" should be "Degrees of Failure:".

Addendum: The previous HTML version lacked some if not all of these issues.

**Comment by Thatguywiththetypewriter** [comment]
Friend of KriosMerew who asked if I could have a wee look. Only given it a 5 minute glance, but issue one of his, to do with dodge, seems to be due to a lack of an action line. 

<button name="roll_Dodge" type="roll" value="&{template:darkheresy2} {{name=@{character_name}}} @{DodgeCharacteristic}">

^How it currently is:

<button name="roll_Dodge" type="roll" value="&{template:darkheresy2} {{name=@{character_name}}}  **{{Action=^{dodge-u}}}** @{DodgeCharacteristic}">

How it should be , with added part of the line in bold. 

Also as a note, my knowledge of the coding language is limited (Only looked at this as a favour, as said).  but it seems that in this set of lines (With the main issue being in bold) : 

<td><span class="tcat">{{Action}}</span> <br>
    			
    			{{#rollGreater() Test -1}}
    			    {{#rollGreater() Unnat 0}}
    			        <span class="tcat" style="color=green"data-i18n="succes">Degree of Succes:</span> <span class="tcat">**1 +{{Test}}** +{{Unnat}}</span>
    			    {{/rollGreater() Unnat 0}}
    			    {{#rollLess() Unnat 1}}
    			        <span class="tcat" style="color=green"data-i18n="succes">Degree of Succes:</span> <span class="tcat">**1 +{{Test}}**</span>
    			    {{/rollLess() Unnat 1}}
    			{{/rollGreater() Test -1}}
    			{{#rollLess() Test 0}}
    			    <span class="tcat" style="color=red"data-i18n="fail">Degree of failure:</span> <span class="tcat">**-1{{Test}}**</span>
    			{{/rollLess() Test 0}}
    			
------------------------------------------------------------------------------------------------------------------

Seem to be displaying as strings. I.e, rather than showing say "15 degrees of succes", it is actually showing  "1 + 14 degrees of succes"

**Comment by clevett** [comment]
@KriosMerew 

#4812 is too old to easily roll back. It has a lot of merge conflicts. I put in a PR #4958  that fixes some things:

- NPCs divs
- Adds the Dodge suggestion above
- Corrects spelling in the translation.json & en.json

---

The degrees of success/fail will take a bit of extra work. As a loyal servant of the Emperor, I will look into it. We will correct these influences of Chaos.

**Comment by KriosMerew** [comment]
Looks a lot better. Thank you!

**Comment by clevett** [comment]
You're welcome. I also saw you put in a pull request for the Degrees. This this issue solve?

Thanks,
Cassie

**Comment by KriosMerew** [comment]
Yeah, just for the colour to be fixed. It is now in the game as expected.

**Comment by Anduh** [comment]
@KriosMerew @clevett reminder this issue is solved and can be closed.
