### ISSUE TITLE
[Shadowrun 5th Edition] - Roll macros do not respect Physical/Mental/Social Limits

### ISSUE THREAD

**Issue by MarkJPerry** [Roll20/roll20-character-sheets#5053]
When rolling large pools of dice my players are finding that the total hits are exceeding the limits for the P/M/S pools. 

Feature Request

Add a toggle for "Apply Limits" which when turned on caps the total hits for a roll to the relevant limit.

**Comment by MarkJPerry** [comment]
Looks like the `sdkh?{Limit|1}` needs to be added where "Limit" refers to the correct limit for a particular roll.

**Comment by clevett** [comment]
Limits are not applied via the Roll macro intentionally as there are so many niche ways to alter them. Similar to playing with a paper sheet its up to the users to apply them.

**Comment by clevett** [comment]
Greetings @MarkJPerry 

#5068 I added a select for limits to the Skill lists. This picking a limit will cause the roll template to show the Limit when you roll. It doesn't apply a limit to the roll itself but it should be easier now to see what your capped at inside the chat window rather than needing to reference back to the sheet.

I hope this helps with your game.

Thanks,
Cassie

**Comment by MarkJPerry** [comment]
@clevett - WOW. Thank you so much. Got some new players this will definitely help with.

**Comment by clevett** [comment]
You're welcome. :) Best of luck in the Shadows Chummer.
