### ISSUE TITLE
[RunequestGQS] Add data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5300]
The game RuneQuest Roleplaying in Glorantha will soon be translated in french (the quickstarter is already translated)
I supose that this game will probably be translated in Spanish and German too (or already is).
So I think that data-i18n tags should be added if possible.

So if @Lockbox313  is able to add them it will be cool and probably very appreciated.

If he doesn't have the time, I can try to add the tags and provide a new html file, but I will need help to generate the translation.json file (cause I have no pro account for the moment)

BRgds

**Comment by Lockbox313** [comment]
That is not something I am interested in doing.

**Comment by Lockbox313** [comment]
You will need to change the function that adds the skills  and use getTranslationByKey to get the translated  skill names.

**Comment by dyvim** [comment]
OK. I'll try to do that by myself. (it's not the first time :))
Someone gave me a script that is supposed to generate automatically the tags... It's a good occasion to test it.

Do you you mind if I send to you the new html file as I won't be able to generate the translation.json file?

**Comment by Lockbox313** [comment]
Who gave you the script?

**Comment by Anduh** [comment]
You mean the [ACSI](https://github.com/Anduh/acsi) script? Yeah it' works on well-structured html,and on some sheets might generate something that is a timesaver on on other sheets. I advise to remove sheetworkers from any file you run through the acsi, as it only expects html in the files, doing quite a number otherwise.

**Comment by Lockbox313** [comment]
@Anduh is this the script you used on the Monstehearts 2 sheet?

**Comment by Anduh** [comment]
Yeah. Monster heart was a sheet it didnt work well for, but the script have done better on other sheet, think there are now like 5 sheet that have been translated mostly by ACSI.

**Comment by Lockbox313** [comment]
Which sheets were they?

**Comment by Anduh** [comment]
Forbidden Lands, Nemesis, Over the Edge, Chronicles of Darkness by Roll20, Cyperpunk2020.

**Comment by dyvim** [comment]
> You mean the [ACSI](https://github.com/Anduh/acsi) script? Yeah it' works on well-structured html,and on some sheets might generate something that is a timesaver on on other sheets. I advise to remove sheetworkers from any file you run through the acsi, as it only expects html in the files, doing quite a number otherwise.
> ACSI can to a limited capacity also generate a `translation.json` file when it inserts the i18n tags into the html file.

Yes I mean this script

**Comment by Anduh** [comment]
> Yes I mean this script
I'm looking forwards seeing someone else than just me use it :D

**Comment by Lockbox313** [comment]
To successfully do this you will have to take out the html that pertains only to Runequest:Glorantha sheet as the file also contains a sheet based on the RQ3 sheet that was done before the rules were released.  After you run that through the script you will have merge back into the file and then it needs tested by someone who has a pro account.  Since you do not have  a PRO the only thing you can  do is tidy up the JSON keys and  data-i18n in the HTML.

**Comment by Lockbox313** [comment]
Here is a version of the HTML with Quick start sheet removed and the sheet workers removed. [https://github.com/Lockbox313/Roll20-Testing/tree/master/RQ%20Translation](url)

**Comment by dyvim** [comment]
Hmmm I didn't remember ACSI was developped for Linux... Do you think a windows executable could be generated with the sources @Anduh ?
I don't have a Linux OS installed at the moment

**Comment by Anduh** [comment]
>  Do you think a windows executable could be generated with the sources @Anduh ?

I doubt it. Pretty sure one or two of the core libraries making ACSI into a command line tool are Unix-dependent.  Making it Windows-compatible is pretty low on the todo-list, and I haven't really had time improving it lately so that will likely not happen this decade...

**Comment by Anduh** [comment]
[Here is the result](https://gist.github.com/Anduh/036c26eecd747699bb7e2dc91d52ace0) of running ACSI, and some minor cleanup before and after, and added back the sheetworkers & rolltemplates.

Unfortunate there seems to be some serious flaw with the end result, as it doesn't want to display at all if tried in a custom game. I fixed some minor html/css mistakes on the sheet, and ran it through a validator, but couldn't figure out why it isn't working. My only guess is that I changed something that the sheetworkers didn't like, which disables the sheet.

Guess the script wasn't much help this time, probably best to do the translation form scratch, unless someone can figure out with a quick glance what's wrong.

**Comment by Lockbox313** [comment]
I pull something together with VBA (I  would have done C# but I don't have VS studio installed on this machine.) It does <div> <spans> and <labels> currently and I am not output any json so the data-i18n placeholders (is that the correctname) are showing.  Here is an invite to the test game https://app.roll20.net/join/4461254/F7DxUQ

**Comment by Lockbox313** [comment]
@dyvim Are you still interested in this? If you are it would help if you did some testing on sheet in the game linked above.

**Comment by dyvim** [comment]
Hello,
I'm still interested but i am at the hospital for at least one week.
BRgds

**Comment by Lockbox313** [comment]
I will have to redo the data-i18n tags  as I had to issue a fix. No ETA on that.

**Comment by dyvim** [comment]
I did some tests in your test game. All seems to work correctly but I can not be completely sure as all the text was in english (logical as fr.json has not been initialized I suppose)

**Comment by Lockbox313** [comment]
It will have to be redone as I had to issue a fix.  I am in the middle of something else so as I said above no ETA when I will get back to it.

**Comment by Lockbox313** [comment]
I wrote something which added the tags and didn't mangle anything but I had to make changes tothe sheet before the OP returned to look at.  I have not had time to redo it.

**Comment by Lockbox313** [comment]
I ran the latest version through the vba app and tidied it up but as this is auto generated it really needs a thorough testing which I do not have time for. Not sure who is going to do the testing as the OP has stated his English is not good enough for testing.  Here is the test game https://app.roll20.net/join/5708059/jCIr0Q

**Comment by Lockbox313** [comment]
The sheet is functioning from  json the actual language  doesn't  matter.

**Comment by Anduh** [comment]
Although if you try the sheet without the json, you should see red for all the text, and notice if some section is missing a tag, but that's a much smaller problem. If no red text is seen in the test game with he json, it means any bugs/mistakes on the translations is minimal.

**Comment by Lockbox313** [comment]
The issue is this was auto generated as opposed to working through thousands of lines of code. That means it needs  a lot of testing .  Somebody has to do that work.  It is very easy to say I want this character sheet done or I want tags in this sheet and then sit back and wait for someone to do that work

**Comment by Anduh** [comment]
Yes, and the massive amount of manual work was also why I turned down to work on this particular sheet's translation tags, beyond offering what my half-assed script generated.
I've helped translate about 8 or so sheets over the last year or so, but it have been those smaller ones that my script worked well with, making reliable heavy lifting with the manual work.

It's possible I'll rewrite the script in python later this spring, as part of a course I'm currently taking, so that combined with me becoming more effective with these kind of things, I might take a jab at this later. 

Lockbox, do you have a gist or a repo where you have the sheet code you have in that linked test campaign? And @dyvim , maybe you know people who'd be interesting in testing Lockbox's current version, and see if they find any bugs with it? If Lockbox would share the current translation.json file, people could start translating it, considering whatever it contains wouldn't change much to a final version.

**Comment by Lockbox313** [comment]
The majority of it is done as can be seen in the test game accept for roll
templates

**Comment by Anduh** [comment]
Have you run the code through some HTML validator? Was the main reason I was asking for the code...

**Comment by Lockbox313** [comment]
If there an been an issue with the display I would have done that but
everything displays correctly.  What HTML validators cannot pickup is
button types being changed from roll to submit this sort thing requires
someone to go press buttons and fill inboxes.

**Comment by dyvim** [comment]
I've done some tests on your test game.
Everything seems OK
The rolls works correctly
No display trouble, no text in red except what is sepcified to be in red.
I think there is no data-i18n tag that miss a line in the translation.json.

Thanks for all the work

**Comment by dyvim** [comment]
@Lockbox313 Do you think my tests are sufficient? Will you submit the modifications?

**Comment by Lockbox313** [comment]
A large number of roll tables still need to be done.  Pressing the same
couple of buttons for 20 minutes would not have caught that.

**Comment by Lockbox313** [comment]
Ok. I finally got this done. I am sure there is something buried in there that I missed but that will have to come out in the wash for the sake of my sanity.  I have not done the hit locations and fumbles for the quick start but any sane person should not be using that now..

**Comment by dyvim** [comment]
thanks a lot
this is very timely because the pdf of the french translation for RQG will be delivered in the coming days
I'll begin the translation as soon as your work will be commited
BRgds

**Comment by Lockbox313** [comment]
This will probably be delayed as someone made a bunch of mostly cosmetic changes a few hours before before my pull request.

**Comment by Lockbox313** [comment]
The merged failed because of the changes made by another contributor .  I have tried tried to fix this but it is difficult because I have no easy way of checking what the problem is because github desktop app requires a 64 bit o/s.  If this pull fails I will abandoned this update and probably any other support for this sheet.

**Comment by dyvim** [comment]
Hello @Lockbox313 
My french translation is almost finished but there are a few terms that I  have questions about...
What are : 
- RCR Leg
- LCR Leg
- LCR Leg
- LCF Leg
- MQ Mod.
There is also a skill Sneak that I can translate but there is no sneal skill in RQG normally...
Thanks for all your work to add the data-i18n tags.
I will close the issue just after your response I think.

**Comment by dyvim** [comment]
I've found that MQ was an abbreviation of Move quietly.
I close this issue as all is resolved.
