### ISSUE TITLE
Dungeon World damage dice is wonky

### ISSUE THREAD

**Issue by Nnesk** [Roll20/roll20-character-sheets#558]
Hello al,,
Couldn't find another report on this problem, so I'm opening a new one.

The damage dice is all over the place, sometimes showing just 18 (as if that was the input, not a roll at all) and sometimes rolling the previous damage notation we put in, or the one before it, instead of the current one. We first noticed it when trying to enter d8 for damage.

**Comment by smalone11** [comment]
Is this happening across all the character sheets in your game? I can't seem to duplicate it in mine based on the information given. From looking at the code for the sheet, it looks to be written correctly. The roll macro being used is `/me rolls [[1@{dtype}]] damage.`, where `dtype` refers to what is written in the _input box to the left of the roll button_.  So the input on the character sheet should be **d#**. 

Based on that having a roll of 18 could be due to _not_ having the **d** before the **8**. The problem of it rolling previous entries I'm confused on exactly what is happening on your end. My understanding is that you had something else written in the input box, such as d6, but then changed it to d8 and when you clicked on the roll button it still rolled a d6. If this is the case then I'm not sure of the problem here. I would be willing to come look at it myself so I can see the problem firsthand and that could hopefully help me figure out where the problem lies.

**Comment by Nnesk** [comment]
Thanks for the reply! It's been more than a year since I've posted this comment, and frankly, I simply don't remember what it was about - and maybe it was fixed since then anyway. 

If I find myself playing again with character sheets, and the problem re-surfaces, I'll repost here.

**Comment by smalone11** [comment]
Sounds good! I realized after I had written it that it said 2015 and not 2016.

**Comment by clevett** [comment]
Hello,

We are looking to resolved old issues that are on the GitHub. Based on the conversation here I'm going to close this one. If this is still an issue please let us know. 

Thanks,
Cassie
