### ISSUE TITLE
[Coriolis] Request: Add missing roll features

### ISSUE THREAD

**Issue by lovecervere** [Roll20/roll20-character-sheets#5756]
Hello,
After playing with the sheet and relying on custom macros for a bit, I realised there are some features that might be useful:
- Modifier query for roll buttons rather than a modifier on the sheet itself
- A button to roll a xd6>6 test where x is armour_rating, counting number of successes without the "failure", "limited success" or "critical success" tags, perhaps "Damage removed" instead
- Buttons to roll weapons directly from their profiles, with a toggle between calling the melee or ranged combat skill attribute, and automatically applying the weapon's bonus as a modifier (something like the FFG Warhammer rolls?), then as well as number of successes then display damage, crit, range, and comments, with the "failure", "limited success" and "critical success" tags perhaps limited to "miss" or "hit"
- Possible method for prayer rerolling (apparently the Mutant Year Zero sheet has an API for this?)
- Initiative button (not 100% necessary, especially if you use the Icon deck instead)

I'm no coder, but I've emulated most of these through macros (though I'm using the default template because I can't get the Coriolis template to display more than the name of the roll). Not sure if they'd be helpful for guiding a request, but here they are:

Armour: &{template:default} {{name=@{selected|name} rolls armour}} {{Result:=[[@{selected|armor_rating}d6>6]] damage removed}}

Attacks: &{template:default} {{name= @{selected|name} Makes an Attack}} {{Type:=?{Type|Melee|Ranged}}} {{Damage:=?{Damage|0}}} {{Crit:=?{Crit|0}}} {{Range:=?{Range|Close|Short|Long|Extreme}}} {{Hits:=[[?{Pool|0}d6>6]]}}

(N.B. weapons on the character sheet currently don't have any attributes tied to them)

**Comment by JBeighel** [comment]
So this request is a bit old, but I started work on it anyway.  
I added the first bullet point, the modifier query, and am looking into some of the others.

To try it out join this game:
https://app.roll20.net/join/8659560/Qj5SVw

**Comment by JBeighel** [comment]
Bullet 2: Also added a button on the Armor table to roll the value per the macro the original posted provided. 

I can probably get bullet 3 as well, but I don't know the game rules.  Damage and Crit I'm assuming are die rolls that would be filled into the table, I can get those rolled and displayed easy enough.  The Pool thought I'm not sure about, I'm guessing its built from Strength for Melee and Dexterity for ranged?

**Comment by Elbilin** [comment]
Hi @lovecervere - just a note for you/anyone else who like me wants to use the cool {{template:coriolis}} roll templates and hasn't found anything else online outlining how to;
Firstly unlike the default template the second {{ }} needs to reference the (what I'd call) sub-template by using a subtemplate=1
So for the armour mod JBeighel's input it'd be {{isArmor=1}} and that'll result in the "Damage Removed"
For Advanced skills it'd be {{isAdvanced=1}} to check that there's points in there
For not advanced skills it'd be {{isNotAdvanced=1}} both of these returning fail / limited success / crit.

Secondly rather than the [[xd6>6]] appears to need to be prefixed with roll= from what I can tell.

Lastly it doesn't appear to support multiple lines from what I can tell reading into JB's fixes.

I've written myself one for the shield (so I don't have to keep changing my armour rating) which is a flat roll & not linked to any attribute [though I'd LOVE for the Armor box on the character sheet to be multi input with equipped boxes and one output roll].

&{template:coriolis} {{isArmor=1}} {{name=Roll Shield}} {{roll=[[6d6>6]]}}

I'm trying to write an initiative macro as well that will take into account Combat Vet and Advanced Reflexes as well - which is working on an extra 'attribute' I added called @{init} - but that's not going so well. I can get it to work for my combat vet, but not be variable based on the init attribute, it uses the modifiers as the weapon mods to init;
&{template:coriolis} {{isNotAdvanced=1}} {{name=Initiative}} {{roll=[[{1d6,1d6}kh1+@{mod-prompt}+@{modifier-pos}-@{modifier-neg}]]}} {{pool=[[@{init}>1]]}} {{reroll=[[(1d6+@{mod-prompt}+@{modifier-pos}-@{modifier-neg})]]

**Comment by nmbradley** [comment]
This seems to me like the original issue was resolved. @Elbilin if there are still outstanding problems with this sheet, please create a new issue.
