### ISSUE TITLE
Fallout: Vaults & Deathclaw Name Change Concern

### ISSUE THREAD

**Issue by Skyeris** [Roll20/roll20-character-sheets#5762]
I understand why the name was changed but how do I update it now? Do I have to rename it on my end? Redownload the fork? Or can I update normally?

**Comment by Anduh** [comment]
You should make a pull request from the roll20 fork to your fork, and merge it so that the name-changes made to the sheet gets applied automatically to your fork. To be on the safe side, do copy the sheet changes you made to the Fallout sheet and save separately from your fork in case the updating encounters troubles.
It's recommended that you'd use [a branch workflow](https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub#GitHub_Forking_Workflow) when you work with git, makes it easier for you to maintain your fork and protects master branch from trouble.

Here is some tips on how to get your fork up to date to Roll20's fork:
* https://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381
* link was taken from https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub#Sync_your_files_with_Roll20

**Comment by Skyeris** [comment]
@Anduh Thank you. Now, if I need to update the sheet, I do the usual and make a Pull Request then. Correct?

**Comment by Anduh** [comment]
Yes.

**Comment by clevett** [comment]
It's best to always keep a fork up to date. There are directions for this in the wiki, https://github.com/Roll20/roll20-character-sheets/wiki

I recommend making branches off an update master for your work and submitting pull request directly from the the branch to this repository.

- Cassie
