### ISSUE TITLE
Pathfinder Second Edition Upstream Changes

### ISSUE THREAD

**Issue by Brendan-McCoy** [Roll20/roll20-character-sheets#5885]
I don't know what automation/build features can't be hooked into this repo that necessitated a move, but can we at least get the upstream changes in this community repo?

**Comment by clevett** [comment]
I updated the current files in this repo, https://github.com/Roll20/roll20-character-sheets/tree/master/Pathfinder%20Second%20Edition%20by%20Roll20

I had to add _ to all translations so that Crowdin wont upload them but other wise the sheet is currently up to date. This wont be a habit as I have to currently manually move the files though we are brainstorming ideas to automate this tasks.

- Cassie
