### ISSUE TITLE
[Deadlands: Classic Anniversary]

### ISSUE THREAD

**Issue by RelativeDimension** [Roll20/roll20-character-sheets#5986]
Two of the skills are linked on the character sheet.  Disguise and Mad Science.  When you enter a value for either one, the other automatically fills in with the same value, so as it is, you cannot have differing values for these two skills.

**Comment by Medieve** [comment]
Oh, I've been looking at Deadlands Classic recently. I have a pull request up but I'll take a look at the skill attributes.

**Comment by Medieve** [comment]
I haven't been able to duplicate this issue and I don't see a problem with attributes in the sheet's html. Let me know if its still the case, I might've fixed it and didn't remember.

**Comment by RelativeDimension** [comment]
I think it was fixed sometime before last week.  I had changed to the other
Deadlands sheet, and we noticed that the style/font of that sheet had
changed, so I loaded up the classic sheet again, and it seemed like the
link between the two different skills had been fixed

**Comment by RelativeDimension** [comment]
I wanted to bring something else up, some comments/complaints I've been
hearing from my players over the past few sessions.  These are for the
*Deadlands
Classic 20th Aniversary* Sheets, but I also have an issue or two for just
the *Deadlands Classic* character sheets as well.  I don't know if I should
open a separate ticket for those issues, but I will include tham at the
very end here

1) Flipping tabs back and forth between skills, combat stuff, etc.
2) Wound penalties, modifiers, etc.
3) Shootin Skills


*1) * I don't know how easy or hard it might be to add some of the combat
skills onto the combat section of the sheet.

As it is, the current layout requires someone be on their Skills+Traits tab
to roll their skill, then switch to the combat tab to find their weapon to
roll damage.  It doesn't seem like much, but when you have fast turns, it
means a lot of switching back and forth.

So I was wondering if the sheets could be formatted so that Each Weapon has
it's appropriate Skill listed next to it perhaps. Something like "Weapon
 Shots/Max  RoF   Range   Damage   Skill"  and have a spot for the dice,
value, and modifiers.. that way players don't have to keep switching tabs
back and forth

*2) * I don't know if it would be possible to apply modifiers to the wound
levels.  -1 for Light, -2 for Heavy, etc..  and then have the sheet look to
see what the highest damage level is, and apply that as a blanket modifier
to all Trait and Aptitude rolls.  Some of my player have been having some
confusion with remembering the wound modifiers, or if they do, they are
adding into the modifiers next to each Aprtitude, which then gets confusing
next session when they forget why.  So this fix is not necessary, but would
be really convenient.

*3) Shootin Skills *(and Fightin as well) should be listed as
Concentrations, such as
Shootin : 4
    Pistols +*mod*

For sake of Advancing, Shootin is a single skill.  If you have Shootin 4,
and you have Pistols concentration, then if you spend 3 Bounty to add
Rifles, you still have a single Shootin skill of 4 but it should be noted
like
Shootin: 4
   Pistols *+mod*
   Rifles  +mod

That way, when you increase the skill, you only have to raise the 4 to a 5
in one spot, instead of having to increase it for each and every weapon
type you know how to shoot.


Okay, not for the issue for the Deadlands Classic character sheet.  This is
the sheet with the different layout/background color.
the main issue is when rolling Guts+Grit from the Core page.
The issue comes into play when you have a modifier to Guts.  One of my
players has a Spirit of 1d6, and a Guts Level of  3..  so when he rolls
Guts directly, the macro command says "Rolling 3d6!!k1"  which works fine.
Now, he also has a Grit of 1, so when he hits the "Guts + Grit" button, it
says "Rolling 3d6!!k1+1"  Fine so far.
Now, this PC aso has Brave, which provides a +2 to Guts Rolls..  So, we
learned long ago that + signs in the character sheet cause issues, because
extra + signs break macros,. so all positive modifiers are just entered as
the number.
So his Guts skill is listed as 3  and  2  (there's a + on the sheet between
the two fields), and when rolled, it rolls correctly with 3d6!!k1+2
However, there is the problem in that when he uses the Guts+Grit, it should
be "Rolling 3d6!!k1*+2+1*"  But instead rolls "3d6!!k12+1"  That *2+1* from
Guts mod is inserted into the Guts & Grit macro without a + sign built in.
So, the output has him rolling his 3d6, but it is keeping and adding them
all, instead of the highest 1.

So, I thought to fix it by making the modifier to Guts a *+2 *instead of
just 2.  And this Fixes the Guts & Grit Macro, making the final result
"Rolling 3d6!!k1*+2+1*"
But it Breaks just Guts, with an output of "Rolling 3d6!!k1++2"  for a
broken result of 0

So, somehow the Guts and Grit macro needs to be fixed to include an
automartic + sign between the !!k1 and the modifiers for Guts..
Which, the Classic 20th Anniversary sheets somehow has working right, but
all the macros on the "Attributes & Abilities" page look identical to me,
so not sure why it works fine on one, and not the other

Anyway, Those are just some of the issues.  Please feel free to contact me
for clarification, or to let me know if I should open a separate ticket for
that last issue.

Thank you,
Joe

**Comment by Baledin** [comment]
I am currently building a new version of the sheet (I had nothing to do with the originals but there was quite a bit I didn't like) called Deadlands - Classic Anniversary - Improved that was recently merged into Roll20. I don't recommend switching mid-game as some attributes do not directly relate and you will end up rebuilding those pieces (primarily the Arcane section but I also fixed duplicated skills), but I am fixing some of the issues listed above while I'm at it. I would also love to hear any additional issues or suggestions and will incorporate as I can.

**Comment by RelativeDimension** [comment]
Ah, I saw that sheet..  I copied the game to a separate table, so that I
could see which of the other sheets I like best.. and at the moment, we're
using Classic Anniversary as they are the least buggy.

With the Classic Anniversary - Improved, I did notice a few things.  I am
not sure how far into development you are, so you may have some of these on
the list of what you are working with.

Some of these Suggestions also come from other people that have brought
these up in the Unofficial Deadlands Discord server, so I may not have seen
these same issues, but I recall hearing them,

First, let me say I like the look of the new sheet.  I like the overall
layout.. I think it the background could be darkened a tad, a white box
could be used for the White Chip selector.. but it's fine as it is.

In no particular order
1) Someone commented that they would appreciate it if the attributes were
ordered as they are in the book's character sheet - basically
alphabetical.  Cognition, Deftness, Knowledge, Mien, Nimbleness, Quickness,
Smarts, Spirit, Strength, and Vigor.  People get used to looking in a
specific place on their physical character sheets, and get lost when using
the online sheets.

2) A Hit Location toggle in the weapon sections - and if possible, one for
melee attacks that automatically uses the +2 when Fightin' modifier to hit
locations.

3) Hit location numbers next to the wound locations for quick reference.
When you score Raises on your attack, you can adjust the hit location, and
it's nice to be able to quickly see what locations are assigned to which
numbers.

4) Concentrations vs Separate Skills.  The book is not too clear on which
is which.  Most Aptitudes with Concentrations Act with the single level for
the overall Aptitude, and then you select different Concentrations.  Like
Shootin, Fightin, etc..  You have your Shootin skill at 4, and then each
different type of gun you spend to add gets added to the skill at the
overall level 4.  And when you then raise it to 5, all of them go up to 5.
So they shouldn't be listed with separate skill values.
BUT.  Some skills, like Languages, Professional, and Trade  are called out
specifically as being raised as if they were separate skills.  So, for
those, each entry will need it's own skill level box.
Sciences are also presented in many NPC stat blocks in various books as
separate skills
I am asking among the Discord to see if we can figure out which specific
Aptitudes should be listed separately, instead of under a blanket level for
all Concentrations.

5) I like how each hex now has a dropdown for the attribute it is linked
to, but it seems to have Shadowrun macro notation.. when you roll, it seems
to want to count if one of the dice are 5 or higher..  so the { }>5 should
be removed.

6)  This is minor..  I came across when statting out an abomination.  It
was a creature with Supernatural Traits.  Deftness and Quickness were at
d12+6, so what I did was add +6 to the modifier for Shootin, and
Quickdraw.. but for Initiative, it needs to roll Quickness +6.  So I don't
know if maybe a Supernatural Traits secion in the Arcana, with a
Dropdown for which attributes you apply them to, and then you can add +2
or +4 or whatnot into the modifier, and it could automatically add into any
Trait/Aptitude roll you make, if appropriate?  Not sure how it would work
on roll20.

7)  Maybe a button next to Grit, that automatically rolls a Guts roll,
including Grit, and any other modifiers to Guts on the sheet, but also
includes a modifier window?  Sometimes when Fear levels are high, I ask my
players to roll Guts + Grit at -3 for Fear, and there is no easy way to do
this without just rolling, and deducting 3 from the final result.

8)  One of the sheet versions has 2 damage lines for each weapon.  I like
this, because for some weapons, I can list damage with a lower die type, in
case they are shooting someone with armor, or whatnot.. but I was wondering
if maybe there could be 2 buttons for damage.. a "regular" damage roll, and
then one that brings up a selector to modify the number and/or size of the
die.
  - For instance, a Shotgun at 20 yards does 4d6 with Shot, or 6d6 wth
Slugs, so "regular" damage might be 6d6, but the modified damage button
could be clicked for the selector to select 4d6.  Or, if someone with a
Peacemaker hits someone with 2 levels of armor, they'd roll 2d4 damage
instead of 3d6

9)  I think that's everything I have in mind at the moment, other than some
of the other stuff I've mentioned above, like some way to reduce the need
to keep switching tabs for rolls, and wound penalties auto-affecting rolls..

Thanks for what you're doing!   And if you would like to ask other
Deadlands Players for insight, feel free to hop over into the Deadlands
Discord.  We have Classic players, as well as those that play Reloaded,
Noir, Lost Colony, etc.
https://discord.gg/MqvaNQ3

**Comment by Baledin** [comment]
A lot to go over here so I'll reference your item numbers. The sheet itself
is an initial draft so we could get started with our game, and is being
actively worked on as we get deeper in. Also, be aware that I personally
haven't played DL in 20 years so I'm quite rusty with the game (and my
players are new). It's part of why I'm reaching out to other groups here to
review it.. you'll find more than I will. :D

1) They should be now. It was one of the things I noticed on the previous
sheet that drove me buggy. However, and this is a temporary solution, due
to CSS Grid, they display left to right instead of up and down. I also
alphabetized the aptitudes. The problem with doing columns is that I can't
use media queries (a problem with Roll20) and wanted responsive columns.

2) Looking at re-adding that already. I'm trying to make sure that rolls
incorporate everything they need (including hit location, wound modifiers,
etc). I'm new to Roll20 so it's taking me a little bit to work out the
macros and the like.

3) Easy enough to add, although I'm looking at rebuilding the whole Wounds
section -- including adding "missing" as an option if you've lost a limb. I
was playing with the idea of a paper doll with selectable areas and the
colors corresponding with the sheet's suggested colors (as the current
wound levels are). Question for you, do you do 1 & 3 for left leg and 2 & 4
for right leg? Or do you roll twice? The sheet needs to allow for
flexibility. If I code it onto the sheet one way and a group plays
differently, it can cause issues. (Personally, I created a custom roll
table and we know to adjust it as necessary--not ideal at all)

4) I went back and forth on this so much. I opted to make them all
consistent and to fit what the GM decides the rules mean. I personally play
it like you list it here, but others may wish to split them out. The
current process is more steps for some, but allows for extra flexibility.

5) Ack, I was experimenting with that and didn't mean to have it in the
final. I'll remove it.

6) I'm trying to find a way to incorporate this functionality myself--I ran
into it with people who have Tough as Nails and the like and I want it to
automatically calculate things.

7) That was one of the common rolls that, for now, I dropped. I'm trying to
think of a good way to work them back in without having their own tab.
Also, the previous sheet had them but without any modifiers, something I
feel is important if you're going to be doing my rolling for me.

8) The lower damage from armor isn't a function of the weapon, it's the
armor... so it should be a modifier on the roll (something that I'm
experimenting with). I saw the two lines and liked it but i use two lines
FAR less often than would make sense to include the extra space. For now,
if I have two ammo types, I just add it as a second "weapon"--this allows
me to keep my notes separate as well. I would REALLY love it if Roll20
allowed nested repeating sections but at this point I do not believe they
do.

9) The next big update will include as much rolling functionality as I can.
I'm leaning towards having optional information in the roll, and a static
wound modifier (the wound mod is actually in my test sheet now -- just not
incorporated into rolls yet). I nearly added it until one of my players had
tough as nails and I realized I didn't account for that in the modifier. :D
I'll jump in the discord now to check things out.

J

**Comment by Stexinator** [comment]
@RelativeDimension  if this is resolved, please close it

**Comment by Baledin** [comment]
@RelativeDimension If you feel any pieces still need worked on (quite probable), add it to the [issues on my repo](https://github.com/Baledin/roll20-character-sheets/issues).

**Comment by nmbradley** [comment]
It seems as though this has been resolved, so I'm going to close the issue. If there are lingering problems, please submit a new issue to this repo, or to the one that Baledin linked above.
