### ISSUE TITLE
Dark Heresy 2 Incorrect Melee Damage Formula

### ISSUE THREAD

**Issue by DaveOfTheEd** [Roll20/roll20-character-sheets#6320]
Present in Dark_Heresy_2ed/DarkHeresy2ed.html:2540
Current Formula is: 
`"/me does [[@{meleeweapondamage}+@{UnS}+(floor(@{strength}/10))]] @{meleeweapontype} damage! (Pen: @{meleeweaponpen})"`
From the rulebook, it seems you should only be adding the strength once, not twice as per above.
I might be incorrect, but regardless the formula is also using 2 different methods of getting the same value, which is inefficient.
E.g. With 25 Str, it has `UnS`=2, and `floor(@{strength}/10)`=2.

If I'm correct, and I'm somewhat new to the system, could the floor be removed, as it is surplus to requirements in this case.
I.e. Formula be changed to 
`"/me does [[@{meleeweapondamage}+@{UnS}]] @{meleeweapontype} damage! (Pen: @{meleeweaponpen})"`

**Comment by Zarzirel** [comment]
You are wrong. Because Unnatural Strength field must be used for bonus you benefit from Unnatural Characteristic (Strength) (same for any other Characteristic), not by your Strength Bonus.
This fields of Unnatural Characteristics are used in other mechanics and rolls in this way too. So be careful and read tooltips when you use this character sheet.

Trait Unnatural Characteristic wording:
One or more of the creature’s characteristics is unnaturally enhanced. This is indicated by a number that is then added directly to the relevant Characteristic bonus. For example, a creature with a Strength of 41 normally has a Strength bonus of 4. If the creature had Unnatural Strength (3) then its Strength bonus increases to 7 (4+3). A creature can have this trait more than once, but each time must be applied to a new characteristic. Successful tests using a characteristic tied to this trait gain a number of bonus degrees of success equal to half the Unnatural Characteristic value.

**Comment by DaveOfTheEd** [comment]
Happy to be wrong! Thanks for the info :)
