### ISSUE TITLE
[Midgard German RPG] not in the Roll20 menue

### ISSUE THREAD

**Issue by hjmaier** [Roll20/roll20-character-sheets#6387]
Dear Roll20 staff,

I am not sure if I am just not patient enough, but this sheet does not appear in the Roll20 Character-Sheet dropdown:

https://github.com/Roll20/roll20-character-sheets/tree/master/Midgard%20German%20RPG

Is there something I need to do, or am I just not patient enough?

Best regards
hj

**Comment by Anduh** [comment]
Weird, it was added to the accepted.yaml and other sheets added this week have appeared in the menu. Seems ther occured some mistake on Roll20's side of things.

**Comment by hjmaier** [comment]
@Anduh Is there someone I can ask for assistance?

**Comment by Anduh** [comment]
you could email roll20 at team@roll20.net but they are extremily swamped with support tickets and you've already posted here and the bug forums, so that not help in a timely manner anyway.

The most practical method is to submit a superficial change to to the sheet and in tha PR's title&body also mention the request to fix the sheet so it appears in the dropdown. Roll20 only updates their character sheets stuff once a week, so it's best the right people see this problem, i.e. the people who handles the GitHub repo.

**Comment by hjmaier** [comment]
Great idea. I'll put it in the PR.

**Comment by Anduh** [comment]
The sheet now appears in the dropdown, so this issue can be close @hjmaier
