### ISSUE TITLE
sheet.json patreon/tipeee

### ISSUE THREAD

**Issue by Tealk** [Roll20/roll20-character-sheets#6507]
Hello,

is it also allowed to add other links there? patreon and tipeee are not privacy friendly services, I would like to offer alternatives there. Or would it be possible to offer further links there?

**Comment by Tealk** [comment]
Or a link to the wish list

**Comment by Anduh** [comment]
I assume the format of the sheet.json doesn't even allow other options.

Maybe it's possible to test this out in the Sheet Sandbox?

**Comment by Tealk** [comment]
If I just add anything, it gets ignored.

**Comment by Tealk** [comment]
I can't find any rules for it, then I would just write that in "instructions"?

**Comment by Anduh** [comment]
Yeah. You can look at https://github.com/Roll20/roll20-character-sheets/blob/master/Shadowrun4thEdition/sheet.json for an existing example, for the format.

Looking at how the patreon & tipeee templates (having both text and images different form eachother) looks like in the sheet template menu for "Shadowrun 4E" and "Patient 13", I'd say it's 50/50 if it's hard-coded to accept only those two options, and that putting anything else would result in an error. There is a tiny chance that there exists a default template it would use if other works than "tipee" or "patreon" is used, but doubt it.

You could just make a PR that only adds your link to whatever other similar service using the same format as the "patreon/tipee" section here, and see if Roll20 approves it, and how it turns out.

**Comment by Tealk** [comment]
It is possible to specify other links there, then the linked text leads to the desired destination but the description is wrong, I don't want to expect this from users.

**Comment by Anduh** [comment]
I mean, instead of having "tipee" or "patreon" on the left side, you could just try to use something else and see what happens.

**Comment by Tealk** [comment]
I have already answered this above, other variables are simply ignored

**Comment by clevett** [comment]
I'll confirm that only Tipee & Patreon are supported as entries in the sheet.json as a key. Anything else would need to be added to the instructions key.
