### ISSUE TITLE
New [Old Dragon] sheet not available to public

### ISSUE THREAD

**Issue by johcker** [Roll20/roll20-character-sheets#6528]
I made a new sheet for Old Dragon RPG, a game very popular in Brazil.
The merge was approved about 9 days ago, but the sheet still unavaliable until today.

The link of the pull request (already closed): https://github.com/Roll20/roll20-character-sheets/pull/6351

Why is this process taking so long?

**Comment by Anduh** [comment]
Seems Roll20 forgot to update the [approved.yaml](https://github.com/Roll20/roll20-character-sheets/blob/master/approved.yaml) file to make the new sheet appear. It's a manual process so they sometimes miss a sheet or two when they update the file after the weekly merges.

**Comment by G-G-G** [comment]
If you have any contact @johcker with the people spamming the sheet request, over here: https://app.roll20.net/forum/permalink/8695648/, can you pass along the information that posting in that thread will not get the sheet approved any faster. No one there has anything to do with the approval process. Since you were the first poster there, maybe you can stop it.

**Comment by johcker** [comment]
> If you have any contact @johcker with the people spamming the sheet request, over here: https://app.roll20.net/forum/permalink/8695648/, can you pass along the information that posting in that thread will not get the sheet approved any faster. No one there has anything to do with the approval process. Since you were the first poster there, maybe you can stop it.

Unfortunately I don't know those guys, I think that my post with the images caught their attention because the sheet currently available on roll20 is completely broken (rules and dice rolls doesn't match). 

Here in brazil we are going through serious problems because of the social isolation caused by the pandemic and the online tabletop RPGs has become extremely relevant, add the fact that the game Old Dragon is celebrating its 10th anniversary and is being in great demand these days. I'll try to stop the spam anyway...

By the way, who needs to update the [approved.yaml](https://github.com/Roll20/roll20-character-sheets/blob/master/approved.yaml) file?

**Comment by G-G-G** [comment]
Thanks for the explanation. I dont know who is maintaining the github now, but hopefully they've seen this. If not, you might have to email team@roll20.net to get someone to update it.

**Comment by Anduh** [comment]
> By the way, who needs to update the approved.yaml file?

In the past I've recalled that Roll20 have told that only they edit it, but I could submit a PR for doing the right changes, so it's remembered when they make the rounds next week, and either approve it or reject it and then does the changes themselves. I've considered submitting another edit to the yaml file also, regarding a sheet categorization that have gone unanswered.

I've conidered writing up a new guide on GitHub submissions & changes, and include sections mentioning common occurrences like this. Having read the yaml file, I'm pretty sure how it supposed to be used and edited.

**Comment by G-G-G** [comment]
I've submitted an approved.yaml before, to call attention to an error in it. We definitely aren't supposed to edit those files, but if you make clear its just for illustration purposes of the changes needed, it should be okay.

**Comment by Anduh** [comment]
While Roll20 is already aware of this "Old Dragon" issue due to the massive spam and messaging done about it, in general issues relating to the approved.yaml seems to fall through the cracks pretty often, and mentions in PR description or creating an GitHub issue seems to be overlooked.

All in all, creating a PR with the requested changes is the most clean--cut and sure way that something get addressed in the following week's pushes, even if the PR itself might be rejected. I made a couple of other PRs suggesting changes to the approved.yaml that have been missed so far when previously brought up.
