### ISSUE TITLE
[Ars Magica 5] .1 decimal in fatigue rolls

### ISSUE THREAD

**Issue by mvy** [Roll20/roll20-character-sheets#6783]
There is a particularity when rolling fatiguing spells when you are down one fatigue level. The roll has a added `.1` that is not supposed to be here, as there is no penalty for being 'winded'. 

Is there a particular reason why this value is `0.1` instead of `0`.

See: https://github.com/Roll20/roll20-character-sheets/blob/299e903794335d7f928c7f34bd7c3794a4209c31/Ars_Magica_5th/Ars_Magica_5th.html#L1058

Cheers

(@Medieve tagging you since you are the referenced and current author)

**Comment by Medieve** [comment]
Hi mvy!

Its an inelegant solution to a problem of radios. Right now the fatigue levels are setting the value of the penalty, but when you have duplicate values the radio 'falls' to the Fresh condition when you re-open the sheet because the sheet can't make the distinction between "0" Fresh and "0" Winded. 

The correct way is probably having the radios set the value to a string and have sheet-workers translate that to values but I haven't had time to get into it, I'm pretty terrible at sheet-workers myself.

**Comment by Riernar** [comment]
Hi @Medieve

I think you could use `floor()` to wrap the `@{Fatigue}` attribute in a sub-roll, as in `[[ ... + [[floor(@{Fatigue})]] + ... ]]`, to completely hide that detail from the user (even in tooltip). I tested that on some rolls and it seems to work fine.

I ended up making more change to the sheet to try and add [inline lables](https://wiki.roll20.net/Dice_Reference#Inline_Labels) (I find them quite useful), and also built a script to avoid very similar HTML (e.g. characteristics, reputations, techniques, forms ...). It also made editing some rolls easier.
Would you mind me pushing the changes to my fork, to prepare a PR once everything work ? Since you're the current author, I though I should ask you.

Cheers !

**Comment by Medieve** [comment]
That sounds a great workaround. I was considering that it would need a sheet worker but yours sounds more sane. Feel free to submit
