### ISSUE TITLE
[Chronicles of Darkness] [NWOD] Conslidate sheets?

### ISSUE THREAD

**Issue by PrimalZed** [Roll20/roll20-character-sheets#6849]
It might make sense to consolidate NWOD-Changeling, NWOD-Demon, NWOD-Hunter, NWOD-Mage, NWOD-Mage2, and NWOD-Werewolf into the Chronicles of Darkness sheet. NWOD and Chronicles of Darkness 1e are the same game.

@kluver, @Tratnis, as recent contributors to those sheets (at least for Changeling and Hunter), can you share insight?

@Reonin As with the community-contributed Chronicles of Darkness setup, can you help with any guidance here? Is there a standard approach for how to handle multiple community sheets for the same game?

* How those sheets differ from the Chronicles of Darkness sheet?
* Is a migration / consolidation feasible?
* Would you support or oppose the effort?

If migration is prohibitively difficult, should there be a way to mark these sheets as deprecated and transition users to the Chronicles of Darkness or Chronicles of Darkness by Roll20 sheets?

I'm willing to accept that the NWOD-* sheets should just be left alone as-is. I'm not sure how else to initiate the discussion.

**Comment by PrimalZed** [comment]
For anyone unfamiliar, crossover campaigns aren't uncommon in Chronicles of Darkness. That's usually still within a single edition, not somehow crossing 1st edition and 2nd edition rules.

The Chronicles of Darkness sheet already has support for 1e Changeling, Hunter, Mage, and Werewolf, and 2e Changeling, Demon, Mage, and Werewolf (among others). However, I'm not sure if the NWOD-* sheets for these have additional features missing in the Chronicles of Darkness sheet's implementation. If this effort seems worthwhile, I can investigate those sheets to see how they behave.

**Comment by Anduh** [comment]
I does make sense, and there was that one WIP attempt by CPP that's now in a standalone repo by me if you wanna pick it up. There was a thread about this at some point, but don't remember if anyone continued working on it.

**Comment by PrimalZed** [comment]
It looks like your standalone repo was for World of Darkness sheet consolidation, not Chronicles of Darkness. They're actually separate game lines, not unlike Dungeons & Dragons and Pathfinder.

I have some more work to do on the Chronicles of Darkness sheet before I want to pull in those other sheets. I'd still like to continue this discussion for what form the consolidation will take.

I'm generally expecting two key steps:

1. Attribute migration, mapping the values from the NWOD sheet to the attribute names that the Chronicles of Darkness sheet uses. If possible, I'd like this to occur in the NWOD sheet.

2. Messaging to people using the NWOD sheet to inform them of the option to switch to the Chronicles of Darkness sheet, along with the steps they would have to perform for the transition. I expect this will be done as a new banner or display within the NWOD character sheet itself.

**Comment by kluver** [comment]
(Sorry for missing this chain earlier. PrimalZed's email bumped it in my
indbox)

I worked on NWOD-Changeling for a friend, rather than for my own direct
play. I do know the systems from pen/paper play though. With that context
my thoughts:

   - The Chronicles of Darkness sheet does seem to cover the same system,
   and is more feature rich for sure with the dice roller that's built in.
   - My friend missed the Chronicles of Darkness sheet as an option -- I
   don't know exactly why, so to speculate: a multi-system sheet like that
   might be hard to discover/search for, likewise since the preview image is
   vampire it might be easy to think it is a vampire only sheet. That might
   sound a bit dumb, but if someone is scanning quickly and only giving it a
   moments thought a sliip like that makes sense.
      - Regardless of what happens to the "other" sheets, this might be a
      moment to ask how the official multi-system sheet could be made more
      discoverable. Could it be listed under multiple names? Or maybe
the "other"
      sheets should have a reference pointing out the "official" sheet.
   - When I showed my friend the Chronicles of Darkness of darkness sheet
   he chose to stay with NWOD-Changling. There were minor complaints, but the
   deal breaker was skill specialties. The chronicles sheet seems to store
   those in one bulk box separate from skills, rather than the more
   conventional textbox-per-skill approach that pen/paper sheets use. Beyond
   matching pen/paper this also matches rules better (skills specialties are
   tied to specific skills I believe) and helps novice players not forget to
   apply skill specialties.
      - My friend's players have more skill specialties than usual, I think
      they traded their birth names for a few extra skill specialties
or some fey
      nonsense like that. Having more skill specialties probably contributed in
      making the skill specialties difference a deal-breaker for his game.

~Kluver

**Comment by nmbradley** [comment]
@PrimalZed @kluver Are either of you able to report back whether this work was (or will be) undertaken?

**Comment by kluver** [comment]
Howdy, sorry for the delay. I can't say that I've done the originally cited
work. I would also say that I do not have a strong interest in doing the
originally cited work myself.

~Kluver

**Comment by PrimalZed** [comment]
I also haven't done any work on this, and at this point have no plans to. Even if I wanted to work more on these sheets, there's additional items I wanted to get in on the CofD general sheet rather than work on migrating any of these in.

Sorry to bring it up and then leave it. I'll close out the issue, as I'm not expecting anything to come of leaving it open.
