### ISSUE TITLE
[Shadowrun6] Translation fixes have been removed

### ISSUE THREAD

**Issue by rpelisse** [Roll20/roll20-character-sheets#7172]
@yagrima I don't what happened, but I did a lot of work in the previous week to fully externalised the strings on the Shadowrun6th-German, in order to be able to have a french version and even an english one. All those changes have somehow disappear from the master branch of Roll20, while @clevett did merge them two weeks ago. Did you know what happen?

It's really much a shame because the CS was completely translated, we played with it in french and the default was still german (so nothing should have broken on this side). I was about to make available in english for the rest of the community...

**Comment by yagrima** [comment]
Hopefully this works.

 

You have implemented translations which disabled the German translation instead of defaulting to it.

 

https://app.roll20.net/forum/post/8786790/shadowrun-6-sheet-german-work-in-progress-translation-en-later see here

 

In order to have it working for the upcoming convention this weekend I decided to overwrite the whole thing and undo it later.

 

Regards

René

 

Gesendet: Dienstag, 11. August 2020 um 19:26 Uhr
Von: "Pelisse Romain" <notifications@github.com>
An: "Roll20/roll20-character-sheets" <roll20-character-sheets@noreply.github.com>
Cc: "yagrima" <avalia@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: [Roll20/roll20-character-sheets] [Shadowrun6] Translation fixes have been removed (#7172)


 

@yagrima I don't what happened, but I did a lot of work in the previous week to fully externalised the strings on the Shadowrun6th-German, in order to be able to have a french version and even an english one. All those changes have somehow disappear from the master branch of Roll20, while @clevett did merge them two weeks ago. Did you know what happen?

It's really much a shame because the CS was completely translated, we played with it in french and the default was still german (so nothing should have broken on this side). I was about to make available in english for the rest of the community...

**Comment by rpelisse** [comment]
@yagrima OK, so it did not only break for me (as I thought) because the translation was missing, it break everywhere. So it's seems we need to have a translation for both German & French for this to work. That's a shame, it would have be nicer to implement progress step-by-step.

Then, let me a rebuild all my changes and creates the german translation file. Then I'll do a Pull Request against your fork, so you can review and comment before we submit to Roll20. Just try to not implement a lot of changes in the coming days, so I can easily rebase on the current content of master ;) ! 

(I'm pretty fluent in using Git & Github, but it might be your case, so please let me know if what I'm saying here is cryptic to you!)

**Comment by yagrima** [comment]
I'm fine with your proposal and will wait some days with new features.

 

I'll take care of the relevant merging between our projects. I included the wild die rules for attributes, skills and attack rolls.

 

Regards

 
 

Gesendet: Dienstag, 11. August 2020 um 19:52 Uhr
Von: "Pelisse Romain" <notifications@github.com>
An: "Roll20/roll20-character-sheets" <roll20-character-sheets@noreply.github.com>
Cc: "yagrima" <avalia@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: Re: [Roll20/roll20-character-sheets] [Shadowrun6] Translation fixes have been removed (#7172)


 

@yagrima OK, so it did not only break for me (as I thought) because the translation was missing, it break everywhere. So it's seems we need to have a translation for both German & French for this to work. That's a shame, it would have be nicer to implement progress step-by-step.

Then, let me a rebuild all my changes and creates the german translation file. Then I'll do a Pull Request against your fork, so you can review and comment before we submit to Roll20. Just try to not implement a lot of changes in the coming days, so I can easily rebase on the current content of master ;) !

(I'm pretty fluent in using Git & Github, but it might be your case, so please let me know if what I'm saying here is cryptic to you!)

**Comment by rpelisse** [comment]
@yagrima Can you update your fork of the Roll20 characters sheets so that its master branch match the content of Roll20's master branch? I would like open a Pull Request against your repository so you can review my changes and test it, but your repo is a behind so there is plenty of unrelated commit appearing inside the PR...

Thanks !

**Comment by yagrima** [comment]
Hey, thanks for the update.

 

I just re-created my fork for the purpose.

 

Best wishes

René

**Comment by Anduh** [comment]
Is the Translation things fixed now, or is this still in the air? If this if fixed, the issue could be closed.

**Comment by rpelisse** [comment]
Indeed, it can!
