### ISSUE TITLE
Dead of Night sheet not available although it has uploaded into this repository

### ISSUE THREAD

**Issue by raskardev** [Roll20/roll20-character-sheets#7450]
When I try to search and select the tab, it does not appear in the dropdown. I don't know if it's a bug or if the file is incomplete, in that case, I can help. Thank you!

![image](https://user-images.githubusercontent.com/11407705/94464821-4270c480-01bf-11eb-9f5c-8b1c48de798f.png)

**Comment by Anduh** [comment]
Are you talking about [this sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/Dead-of-Night), added 4 years ago and never updated since?

The Dead of Night 2E sheet seems to have intentionally been removed form the list, likely doe to being created forever ago and being sub-par in functionality/having no users for a long time.

If a new sheet adhering to the minimum requirements is submitted, it will be surely be accepted.

**Comment by raskardev** [comment]
Oh, snap! Yeah, I'm talking about that sheet 😅

Can you link me the minimum requirements, please? Maybe I can spend some time and learn at the same time 😁

**Comment by Anduh** [comment]
check the repo's readme file.

#1 to remember, dont use `<table>` in sheet layout or design.

For general advice and info, see the Roll20Wiki's article on [Building Character Sheets](https://wiki.roll20.net/Building_Character_Sheets) (The wiki, not the Help Center version).
