### ISSUE TITLE
[Pathfinder Official] AC is calculated incorrectly

### ISSUE THREAD

**Issue by dude-rtfm** [Roll20/roll20-character-sheets#7616]
Hello,

It seems like there's an off by one error or something similar in the "Additional" tab of the character sheet.
An AC bonus added to the Deflection column gets counted in the Totals line under @{ac_natural_items}. Screenshots are attached. It affects the other AC types too.

![Screenshot from 2020-10-31 13-37-06](https://user-images.githubusercontent.com/26977664/97779438-f924e380-1b75-11eb-83a9-b0e5cf136716.png)
![Screenshot from 2020-10-31 13-37-14](https://user-images.githubusercontent.com/26977664/97779439-faeea700-1b75-11eb-88a7-bd3ff2bf9f72.png)

**Comment by Kraynic** [comment]
There is something off in your display.  The equipped checkbox is one spot out of place to the right, pushing everything else over.  The 7 and 4 are actually on the AC line, so  your 1 is actually entered in the NAT column due to the entry fields being pushed over.

Which browser are you using?  It might be that this is browser specific for this display issue.

**Comment by Almos80** [comment]
I have the same issue of misalignment in the "AC Items" repeating section when using Firefox 85.0.
Looks fine in Chrome for me as well.
