### ISSUE TITLE
[The Burning Wheel] Delete Skill box overlapping skill info

### ISSUE THREAD

**Issue by aureyia** [Roll20/roll20-character-sheets#7756]
![image](https://user-images.githubusercontent.com/19798820/99907603-a69e9900-2cd5-11eb-8966-714ccd883f76.png)
The delete box is now overlapping the other elements. This on skills and being learned skills.

**Comment by Seraaron** [comment]
I noticed this too while developing the sheet, and tried fixing this a few times, but the way that these elements overlap is very strange. I think it's partly because the Add/Modify/Delete buttons are built in by Roll20. Since this such a minor graphical bug that you only notice very infrequently while actually using the sheet, I gave up on trying to fix it. It just wasn't worth the effort.

If anyone else wants to fix it though, be my guest.

**Comment by aureyia** [comment]
I'll have a look into it and see if I can come up with something.

**Comment by Seraaron** [comment]
Nevermind, I managed to sort of fix it:
![See](https://i.gyazo.com/6558349feea6ab3976f47e168ad2664a.png)

I'll add it to my latest pull request.

**Comment by Seraaron** [comment]
This can be closed now, I think.
