### ISSUE TITLE
Character Sheet translations

### ISSUE THREAD

**Issue by reveblve** [Roll20/roll20-character-sheets#7921]
https://wiki.roll20.net/Character_Sheet_Translation

**Comment by Anduh** [comment]
> Why didn't they make Character Sheet translations code?

Because whoever created the sheet made it in their free time and just didn't have the interest to go the extra mile to create it? Who knowns.

It's not an easy thing to do, and not all sheets have them either. Don't know many people who want to volunteer their time to make something that sounds like a demand being taken for granted...

**Comment by Anduh** [comment]
What char sheet did you want translations for? This issue seems pointless atm, so could be closed.
