### ISSUE TITLE
MERP: Most Recent Update to Roll20 destructive of user data!!

### ISSUE THREAD

**Issue by bigmc10** [Roll20/roll20-character-sheets#8321]
The new changes to the sheet are good prospectively, but you erased data people already using the sheet had in their "languages" and "body development" fields. Not good coding practices, to say the least. I don't think there's anything you can do to retrieve that data, is there? And I don't think a revert would help. Let me know if I'm wrong.

**Comment by Reonin** [comment]
Hi @bigmc10 taking a look at the history of the repository a fellow community author @LyricalStreetPoet made changes to the body development fields [here](https://github.com/Roll20/roll20-character-sheets/commit/f55cde0030d7e3da808bc210012c7dc7b7dff7b9#diff-81d84c4692582739ea913de813e606375ac279a056c81b449678020379c7eead). Good news is the data for the body development and languages is likely still there and the author can take efforts to help migrate the data into the new inputs! 

Cheers!

**Comment by bigmc10** [comment]
I already attempted to (re)populate the new pulldown fields. So I'm not sure a data migration would help me specifically anymore. It was probably the right idea the first time, but now won't it overwrite my (new) data?

**Comment by LyricalStreetPoet** [comment]
@bigmc10 
I'm SO SORRY if anything broke.  It wasn't intended.  Is there anything else that is not working?  I tested with my group's sheets and thought everything would carry over since the variable names were kept the same.

**Languages**
This should have kept your original values.  I tested with my groups sheets and it DID preserve the data.  I guess if you had typed the language slightly different than the proper case spelling from the book or you had a custom language, then it wouldn't bring it into the dropdown.   That was an oversight.  

**Body Development**
I changed it from checkboxes to text fields.  Our group likes to keep track of our rolls for each rank, so we always fill in the rolled value inside the rank.  But it still should have your body development ranks preserved.  They will just show a 1 in the field instead of a check.   If you were keeping your rolled value total in the rank bonus column, then it is indeed lost.  

This last one was indeed a bad practice as it changed how a field was calculated and used my groups house method.  I think it's better than the book, but isn't something I should have changed and instead should have added a new field to preserve the old method.

Unfortunately neither of these are retrievable.  A roll back will not fix it either.

My intention was to make the sheet easier to use (especially for new character creation).  I'm sorry if I caused your group to have to re-do anything.  I'll definitely take these lessons learned for any future updates.

**Comment by LyricalStreetPoet** [comment]
@Reonin 

If you want to revert the sheet back to the original, feel free.  I can just continue to build this version under a new sheet.  

If you don't want to roll back, then I'll just be more mindful of the updates when I touch an existing variables.  

I have LOTS more changed already in a new pull request and have even more changes for this weekend.  Note that I reviewed my current pull request and none of them should break anything since no existing formulas and fields were touched.

**Comment by bigmc10** [comment]
I don't think reverting is necessary. And I appreciate all the work you and others do on this sheet!

Yes, some of my sheets where I had typed the character's race correctly, it worked seamlessly with your new pulldown field. But if someone had anything other than one of the <option> values you provided, it didn't.

Anyway, keep up the improvements. I've actually written a bunch of API scripts and rollable tables for MERP (to automatically reference the results of attack rolls / crits / fumbles, for example), but I'm not sure how they could be incorporated into the sheet itself.

**Comment by Reonin** [comment]
Hey all,

Thanks for keeping up the communication on this. I don't think we want to revert on our end, but I do believe the data is still there. (Migration of the sheet data is something I'm a little fuzzy on. But I'm sure there is documentation available to help if that's something you still want to consider.)

Warm regards,
Corey J

**Comment by LyricalStreetPoet** [comment]
@Reonin I'll do some research to see if I can add a migration script.  The languages might be recoverable, but the bodydev calculation was completely overwritten, I'm pretty sure.  

@bigmc10 That's one of the challenges of going from a free text field to a dropdown.  I wish roll20 gave us a combo box option that would allow for both.  They have one on character sheet selection for new games, but I'm not aware of that being available to sheet developers.  

My latest pull request adds a weapon section that also adds attack rollers for those weapons.  I also created a new roll template for weapon attacks that shows the criticals for the weapons and also gives you a OB parry option.  

My upcoming plans for the sheet:
- Improve weapon section
- Convert entire sheet from tables to grids for layout. This will help with alignment and fix some of the repeating sections that won't let you delete.
- Add default secondary skills (I won't touch existing ones) with auto-calculations for bonuses.
- Add auto-calculations to background options so their bonuses automatically get calculated in when you select them.
- Add a vision section to show vision for the different races under different lighting conditions.  (Would be nice to incorporate that into the token).

I'd love to see your roller tables and scripts.  Do you have a git for them?  If so, I'll see if I could add them to the sheet. 

Our group loves MERP, but the constant referencing to the book really slows things down.  The more we can automate, the more we can get to the action and role play!

**Comment by bigmc10** [comment]
I do not have my code in a repository. When I first started tinkering, I didn't know how Roll20 sheets were developed and didn't think my work would have much of an audience. Most of what I've done could be done in revisions to the sheet, but it's mixed in with lots of other stuff that wouldn't be useful in a sheet. For example, I manually build the html to resemble the template outputted by the sheet (see screenshot below). That will be totally unnecessary when you create your new critical template. I think maybe making the attack, maneuver, and crit tables actual rollable tables might have some value and allow users to decide on their level of automation. I have done the annoying data entry to build all those tables.

![Screen Shot 2021-02-19 at 6 07 36 PM](https://user-images.githubusercontent.com/69563866/108571154-8afb5c80-72dd-11eb-9cc3-6549c0290960.png)

**Comment by Aspire2Hope** [comment]
It looks like there are some great changes to the MERP character sheet but in your push for automation, but I'm losing flexibility. For example, I can't add my own language groups because there is not a **user input option**. So in your next iteration, it would be good to have that across the board.
**Professions:** Need to add the additional professions from MERP2 (we didn't have them in this game but we could have been)
Ranks stop at 15 can we allow these to check up to 20 or again user input the rank bonus value .
**Combat tables and Crits:** Looking forward to this.
Finally - can we set up a **change log and requests** forum post on Roll20 and perhaps Discord (https://discord.gg/V4ET2EyR) so GMs are aware that things are happening. It was a bit of a shock to find the sheets all changed and have to spend game time getting them into a useable state. If I'd known I would have taken action a little earlier.

**Comment by bigmc10** [comment]
Agreed, the latest update seems to have erased a few fields under the NPC/Creature tab as well, such as Defensive Bonus ("spec" columns). I know there is some crossover between the Personal and NPC/Creature tabs, so I assume this was an unforeseen consequence.

As I said, I fully support upgrading the sheet, but more care has to be taken. This is the second such problem. I agree some kind of group forum for planning would be good.

**Comment by jamakkon** [comment]
It's great to have several people developing and/or sharing ideas about MERP character sheet. I noticed the commits only yesterday, so I come late to the discussion. 

The weapon section looks great. I had something similar in mind originally, but gave it up due to the complexity with parry and weapon-specific armor bonuses. However, I am not sure if the drop-down menu of weapon names helps. It prevents adding weapons outside the predefined list which is fairly short. 

In my initial efforts, I did not want to include too much of the published content in the character sheet as it is someone else's work. For that reason, I would not republish the critical and fumble charts inside the sheet.

**Comment by LyricalStreetPoet** [comment]
@jamakkon I've totally redone the character sheet and have been holding off on re-publishing it until it is well tested and vetted.  The community on the [ICE discord channel](https://discord.gg/wESAMpau) has given some great feedback on the changes.  

I agree on the book material.  I've been putting it in for my personal games to make things easier, but will strip it out when the changes are published.  Here is my latest changelog:

02-28-2021

GENERAL
- Converted entire sheet from tables to CSS Grid
- Converted most autocalculations to sheet workers.  Sheet now loads and runs 10X faster.  
- Reskinned to condense space and look more like the old book material  
- Changed font for text fields to feel more like filling out a paper sheet (left the labels as the original font)
- Changed roller icon from d20s to d100s  
- Added broadcast toggle to the top menu (moved from settings tab)
- Tagged all adjustments in the rollers so you can see what all is included on every roll (let me know if i missed some). 
- Added fumble queries to rollers where the fumble can vary.
- Added parry queries to the melee OB rollers.
- Added helmet modifier to orientation global roller.  You can pretty much use this for perception rolls now.

PERSONAL (Player)
- Added player/npc toggle
- Addded advanced classes
- Added homebrew options for race and class (opened race/class autocalc fields to support)
- Added a way to track your original rolls and background adjustements for stats
- Added stats SM rollers
- Changed DB special to include adrenal defense calculation
- Added cold / heat resist
- Added vision area and autocalc for book races
- Added custom language area
- Added some BG option autocalculations (need to do more)
- Renamed the HP field maxium to support token health bars.  This might break some sheets until you hit "recalculate/upgrade"
- Fixed some repeating sections so you can delete.
- Added Ambidextrous roller / tracker
- Added point-buy and rolled stats
- Added a ranged and melee DB for shields that vary the DB.
- Opened all of the helmet and greaves modifiers to be customized instead of hard coded at -5

PERSONAL (NPC)
- Fixed racial defensive bonus (accidentally broke on last update)
- Added stats section
- Added creature templates (have about half of them populated, need to do more)
- Added primary and seconary crits to attacks
- Added autocalculations to compute the crit types based on the attack size and type
- Added a weight field (for encumbrance) and linked it with the Player weight
- Fixed some calculation bugs that existed before for encumbrance and other stats
- Moved some of the dropdowns to the sections they affected (speed, criticals, quickness)
- Added an NPC quick stats generator.

SKILLS
- Added a primary/secondary toggle
- Autocalc background ranks
- Opened a lot of locked fieldss to support home brew
- Added a martial arts and adrenal defense skills to support advanced professions
- Added standard secondary skills (the custom skills section still exists)
- Fixed some wrong text and labels

SPELLS
- Fixed powerpoint calculation to include multipliers
- Added rollers to learning spell lists and determine success/failure.
- Added cast rollers to output the spell details.
- Changed spell description to support longer description (multi-line).
- Renamed the spell point maximum field to support token bars.  This might break some sheets until you hit "recalculate/upgrade"
- Changed collapse arrow from character to an image.

EQUIPMENT
- Totally rewrote the weapon area that was added in the last release.
- Weapons now support templates and will auto-populate the book weapons with stats.
- Let you name your weapon now! (GLAMDRING!)
- Added melee and ranged rollers since some weapons can be both (e.g. daggers)
- Added a note section to weapons
- Added a modifiers section to indicate attack modifiers.
- Changed collapse arrow from character to an image.

JOURNAL
- Added a new journal section to keep track of your adventures by date and xp.
- Added a journal broadcast to publish your journal entry to the chat.

SETTINGS
- Added a character creation settings for point-buy and rolled stats
- Added a font control so you can select the fill-in form font from a list of options.  (We can add more if you want, just send me the Google fonts link.)
- Added a recalculate/upgrade button to run all of the workers to update your sheet to the latest version.  Not all workers run at load any more to support home brew values.

ROLL TEMPLATES 
- Removed the bonus and penalty section (they are tagged in the rolls themselves now)
- Added critical info to attack rolls
- Added parry info for attack rolls
- Added melee/ranged attack templates for weapons
- Added conditional modifiers to attack rolls (this might be removed when the GM section tab is finished)
- Made the main roll bigger so it stands out
- Fixed some bugs in the templates
- Woud like a lot of feedback here.  I thought about having different colors for the different actions to make it more obvious (e.g. attacks reddish, moving maneuvers blueish, static maneuvers: brownish)

PLANNED FEATURES
- New quick reference sheet to have all the commonly used things on a single page.
- Racial sleep needed tracker.  
- Rest button to simulate a rest and heal / replenish power points.
- Injury tracker
- Currency Exchange button to automatically recalculate to the largest denominations 
- More background option automation (skill bonuses and special features like Lightning Reactions)
- Add all background bonuses for secondary skills
- Add forage action
- Deduct from powerpoints when a spell is cast?
- Charactermancer?

**Comment by bigmc10** [comment]
@LyricalStreetPoet I'm once again impressed at your dedication to improving MERP on Roll20! I think almost all of the stuff in your change log and planned feature list is good. But as I urged you on Discord a week or two ago, I would say publish this as a new, distinct sheet given the vast scope of the changes.

**Comment by LyricalStreetPoet** [comment]
This is why I never do community development.  I'm going to ask the admins to roll my changes back to Jamakkon's original.

**Comment by LyricalStreetPoet** [comment]
@Reonin, who can we get to roll these changes back to their original?

**Comment by jamakkon** [comment]
I just made a pull-request containing fixes for encumbrance calculation (negative ST bonus should not yield MM penalty) and misaligned section boxes.

**Comment by LyricalStreetPoet** [comment]
@jamakkon, gonna let you roll with this and am stepping away.  Sorry to have messed anything up and thanks so much for this original sheet.  It was an inspiration for what our group is using now.

**Comment by jamakkon** [comment]
I don't see anything messed up. But if you publish your strong vision as an alternative sheet, I might start using that. :-)

**Comment by bigmc10** [comment]
@LyricalStreetPoet I will urge my group to consider your new sheet if you publish it as well. I just know there will be grumbling and resistance if the existing sheet changes dramatically under their feet. I appreciate the huge amount of effort you have put into this. This is _absolutely not about a judgment of your work_ but just trying to figure out best practices for community development. (I.e. when are changes significant enough to be a recognizably different product?) I suspect you would have an appreciative audience for a new sheet. Again, thank you.

**Comment by LyricalStreetPoet** [comment]
@jamakkon I might.  I just did it as a special project for my own MERP group after we started using your sheet.  I've spent WAY too much time on it and don't have the time and dedication to support it.  So I might not.  I published the source in that discord link if you want to try it out.  

But I think I'm done working on it outside of our personal group.  We're actually changing everything to make it a MUCH simplified sheet (resembles the DnD5E sheet now) where everything is on one page.  I'm also looking at a charactermancer to handle the difficulties in MERP character creation and leveling.  The community won't like it because it's significantly different than the book sheet.  Here's a rough first draft:

![image](https://user-images.githubusercontent.com/32119569/111039535-35a1ff00-83f4-11eb-9650-e9c15a256338.png)

There are a few things I did break in your sheet by changing them from open to auto-calculate (e.g. NPC DB).  By making the languages and races dropdowns, it also broke anything that didn't match the exact book spellings.  I saw examples of people adding flavor text to their languages (e.g. Kuduk (Hobbits)) and those were blanked out on the update.

The weapons section shouldn't have been published.  It was experimental and I've totally rewritten it since then.  I'd suggest taking my first publish and just going from there or rolling back altogether and going from there..

**Comment by jamakkon** [comment]
@LyricalStreetPoet I claim no ownership of the sheet. Open source is open for people to change it. Of course, with an active Roll20 community, you might want to do major rewrites carefully, as alternative sheets for instance. The community then gets to decide which one to use. A lot of your changes make the original sheet obsolete, which is great, but there may be some users that prefer the old way — at least till the end of their campaign. 

Although I was not aware anybody using MERP sheet until yesterday, I was aware that people tend to house-rule their systems. For them, a strongly codified attributes/items/skills is a complication or a hindrance. I was aware there professions other than the six listed in the book, and not leaving that open to the users to decide was a mistake. So, while your approach with complete drop-down lists would suit me fine, there are probably some that would like to have that profession as a text field even if they have to add the level bonuses themselves. In Rolemaster family, a codified sheet is never complete enough (just take a look at Companion 2 skill list). 

I skimmed through the Discord discussion and I have to admire your energy. I know how much work goes into a sheet. Like I said on the Roll20 forum, writing character sheets for Roll20 is like eating with six-foot chopsticks (in a dark restaurant). Hah hah. 

p.s. A simplified action page is a great idea!

**Comment by bigmc10** [comment]
@jamakkon  I think an expanded Class pulldown with all the classes from the book _plus_ a "custom" option (with no level bonuses attached to it) would be a good, relatively minor enhancement of the original sheet.

**Comment by jamakkon** [comment]
@bigmc10 It would certainly combine the best of both worlds. It is simple unless someone wants to type in those class bonuses. IIRC, marrying an auto-calc field with editable field causes problems. I might be wrong, and/or that may have changed, or they may be JavaScript spell list somewhere that does that.

@LyricalStreetPoet Re: regarding HTML tables. I started the layout with CSS tables, but captured by the aesthetic of the original paper sheet, I could not figure out a way to span elements (e.g., headings) across multiple cells horizontally or vertically. So, I resorted to HTML tables. Roll20 discourages their use for sheet layout for a good reason, but I think they said somewhere that if you have an actual table in your sheet, then using an actual table makes sense. I might be wrong, and/or that may have changed.

**Comment by jamakkon** [comment]
RE: rollback.

@LyricalStreetPoet It would be best if you removed the changes you want to remove. It is sort of the spirit of open source projects. If I do it, I would be removing someone else's work and it would make me look like a... (browsing through a dictionary) ... a curmudgeon, or worse!

**Anyone** can checkout an older version of the sheet predating the latest batch of changes and make a new pull-request for that. Of course, you can edit that version to taste either by hand or by cherrypicking (literally, `git cherrypick`) versions from your branch history if you have such increments available. Most likely, you just need to find an older versions of the sheet files, replace the latest files with those and make a pull request.

To find an older version, 

1. Go to `https://github.com/Roll20/roll20-character-sheets/` and there to folder for `MERP`. 
2. Click `History` in the blue bar above the file listing. It opens the version history with all the commits made to MERP files.
3. Click the button `<>´ of the commit you like. (The tool tip for the button says _Browse the repository at this point in history_. Clicking that you'll get all of Roll20 character sheet projects. 
4. Again, go to folder for MERP. Now the folder contains the versions of the files that were included the commit you chose.
5. Click the file you want to download. Click "Raw" button in the light gray bar above the file and in your browser "save as ..." 

Once you have replaced and edited the files you want, you need to make a pull-request the normal way. Writing a justification for the changes would help the Roll20 developer who is doing the merge and reviewing the changes. 

Alternatively, you can `git clone` the whole project, checkout an earlier version (`git checkout -b oldversion <git-hash>`) and find the files that way.

**Comment by bigmc10** [comment]
@jamakkon Hang on a second. Do you have any actual game need to revert these changes? The data lost when a few fields were converted to drop down or auto-calc is lost. Reverting won't fix that. But reverting might jeopardize more data. My group has now adjusted their sheets to the changes.

Let's make sure there's a practical reason for any reversion. I think @LyricalStreetPoet was feeling understandably unappreciated when they suggested removing everything (Again, I personally admire and appreciate your work, LyricalStreetPoet!!).

The only thing that is in my opinion slightly in need of removing or revising is the new weapon list. And with the contributor's explicit permission and encouragement, I'd feel comfortable doing that.

**Comment by LyricalStreetPoet** [comment]
You guys do what you want to this version.  No need to get my permission since it's open source and I have no ownership.  I'm abandoning this project.

**Comment by jamakkon** [comment]
@bigmc10 I am very much aware of the problems in doing/reverting changes. If no rollback is needed, great. 

@LyricalStreetPoet You do what you think is right. Take care.

**Comment by nmbradley** [comment]
@bigmc10 are you able to verify that you feel this issue has been resolved?
