### ISSUE TITLE
[GitHub] automatically delete branches after merge

### ISSUE THREAD

**Issue by Stexinator** [Roll20/roll20-character-sheets#8655]
Hello @mperes @nmbradley , is it possible to automatically delete the branches of the pr after merge?

**Comment by aureyia** [comment]
If you are doing this from a fork. Then all you need to do is setup the auto delete on the forked repo not on this one. Then when you merge it will delete the fork's branch.

**Comment by Stexinator** [comment]
@aureyia I set it up like this


![grafik](https://user-images.githubusercontent.com/69796777/113666907-49b5e500-96b0-11eb-8a7e-496b70ec32a3.png)

**Comment by nmbradley** [comment]
@Stexinator Did this resolve your issue or is there some configuration missing on our end?

**Comment by Stexinator** [comment]
@nmbradley the issue is not resolved. And I dont know if you have to configure something

**Comment by aureyia** [comment]
Strange. It works fine for my forks to other repos. I'll see if the same thing happens when I merge my next PR (enabled the auto delete)

**Comment by aureyia** [comment]
Update: Looks like that didn't work for me. (weird because it works for my other repos) there might be some config @nmbradley :/

**Comment by Stexinator** [comment]
@nmbradley can you check if the last checkbox (automatically delete head branches) in my screenshot is checked for this repo?

**Comment by Stexinator** [comment]
@nmbradley @mperes any updates on this?

**Comment by nmbradley** [comment]
Hi @Stexinator 

After some experimentation, I don't think that this is a change we will make to the repository because it would have lasting implications for dozens of users, some of whom have different working styles and might not be expecting this to be the default behavior.

If users want to delete their local branches, that is something that they can enact themselves.

Apologies for any inconvenience.
