### ISSUE TITLE
Das_Schwarze_Auge_4-1 - PA_Aktiv no more calculated on new character

### ISSUE THREAD

**Issue by FKueng** [Roll20/roll20-character-sheets#8717]
When creating a new character on the said sheet the value for PA_Aktiv is not calculated correctly. It still works on existing characters but not on new ones. Also cloned characters seem to be affected.

**Comment by FKueng** [comment]
It seems to be related to the wounds a character has taken. Having him take a wound and removing it again fixes the issue.

**Comment by kreuvf** [comment]
> It seems to be related to the wounds a character has taken. Having him take a wound and removing it again fixes the issue.

Thanks for reporting this. These are some side effects of the ongoing efforts of switching to sheetworker scripts - it is a bug nonetheless. I have a hunch for the root cause and for the next new feature release I plan on adding more code to stabilize the sheet against such issues. Some attributes are only set via sheetworker scripts. On a new sheet, they do not exist yet and when trying to access them they will taint everything that relies on them.

Unfortunately, I know of no way to automatically test individual character sheets (unit tests), so finding bugs is a manual process.

(By releasing new stuff now and then, people will complain if stuff breaks I haven't found in my testing. Therefore, this kind of feedback is very valuable to me and all other players!)

**Comment by Necrask** [comment]
I'll just add that for existing characters, if you use the Trefferpunkte feature to determant damage I get the following error message in chat:
![Dmgroll](https://user-images.githubusercontent.com/67807029/114685345-10195580-9d12-11eb-9893-3d6c97a83f86.png)

I think there may be a common cause.

**Comment by kreuvf** [comment]
> I'll just add that for existing characters, if you use the Trefferpunkte feature to determant damage I get the following error message in chat:
> ![Dmgroll](https://user-images.githubusercontent.com/67807029/114685345-10195580-9d12-11eb-9893-3d6c97a83f86.png)
> 
> I think there may be a common cause.

No, there is isn't, see: https://github.com/kreuvf/roll20-character-sheets/issues/69.

**Comment by kreuvf** [comment]
> It seems to be related to the wounds a character has taken. Having him take a wound and removing it again fixes the issue.

The latest version/Pull Request (https://github.com/Roll20/roll20-character-sheets/commit/8ef92ddf209566383d85f19e447348c4c8cedf4c) should fix this. When version 20210425 is live (~tomorrow), please tell me whether the issue persists or not.

**Comment by kreuvf** [comment]
@FKueng: Please verify that this bug is gone and report this here. :)

**Comment by FKueng** [comment]
Thanks for fixing it @kluver
