### ISSUE TITLE
[Mutant year zero] Wrong names and descriptions of couple of conditions

### ISSUE THREAD

**Issue by mdanielak** [Roll20/roll20-character-sheets#9112]
Hello,
I see a couple of wrong descriptions in the new Mutant character sheet, at least according to the rule book that I have.
First of all, 
`	"condition-sleepy": "You need to sleep for at least one Quarter Day of each day. After one day without sleep, you become SLEEPY. @{sleepy}",
`
The condition should be SLEEPLESS and the proper description according to the rulebook should be
`Every day, you must get at least four hours of continuous sleep. After one day without enough sleep, you become sleepless.`
The same with Hungry (should be Starving), and Thirsty (should be Dehydrated). 
And what is `pack rat talent`? In my rulebook it is called `pack mule` and the description says `You can carry twice as many objects as normal` instead of `You can carry additional items`.
Please have a look, thank you and regards

**Comment by vince-roll20** [comment]
I believe that these issues stem from the fact that some of the updates to the MYZ sheet were based on the Forbidden Lands sheet.  I'll have a look on Crowdin and see if I can update to the proper MYZ wording.

**Comment by dwarfwing** [comment]
Hi, 
You are correct, these are most likely from the fact I based this on the work I had done on the FL sheet earlier (not published). However, most of this is pure translation so can be fixed by Crowdin updates. 
Edit/Update: Updated in Crowdin. 

However, the "@{sleepy}" part, which of course can be removed from the translation, is referring to the name of the attribute used and could be useful to check the actual value of it (perhaps not used that often). These attribute names, as stated, is from FL. In order to change these it would reset any sheet with a condition set, which isnt a great user experience. Instead, I will remove them from this explanatory text in the translation. 
Edit/Update: Removed from translation in Crowdin. 

Finally, again, Pack Rat is the FL term, and this too can be updated in translation. 
Edit/Update: Updated in Crowdin. 

When stating it is updated in Crowdin, it will means will sync back to Roll20 on a recurring schedule. I believe it will be part of the Sunday review of community updates, so hopefully this will be all resolved this weekend. 

Best Regards,
Richard

**Comment by mdanielak** [comment]
Sure, I know that @{sleepy} is a variable.
Last thing, I would do it myself in crowdin, but shouldn't the base file https://github.com/Roll20/roll20-character-sheets/blob/master/Mutant%20Year%20Zero/translation.json be corrected? I thought, that the other languages depends on this one, so if there are mistakes in there, other translations might be affected. Is it correct?
Thank you for a quick response! :)

**Comment by dwarfwing** [comment]
Correct, but even so the English translation can be fixed in Crowdin. You could in theory have an empty string for a translation item in translation.json (haven't tried this yet), and then only use Crowdin to fill it. However, then there is the gap between something being added in the json file and the sync between the Crowdin update. 

The things that would affect the other translations are the identifiers of the translation, those smaller ones shown underneath the translation.json string in Crowding (e.g. condition-hungry, attack-abbr, aso). In this case the conditions are still using the FL identifiers but shouldn't really show for users but only affect what translators see in Crowdin. Since changing those will definitely affect other sheets, I havent changed them yet. If I update those, then there would again be about a weeks difference between the Crowdin sync, which will leave some players with translated sheet revert to English during that period. 

The only way to do a seamless update of the translations is to add non-used ones to the trnaslation.json, publish that. Then you add translations to those, wait for the sync, and then you do another publish where you have started using these new identifiers. A bit cumbersome, but only way I know. 

I will update the translate.json with these new strings, since they are the correct ones as you pointed out. I am waiting for more feedback before I publish new version of the sheet, since I believe the Crowdin fixes for this should be sufficient for now. Is that an Ok solution for both short and long term?

**Comment by mdanielak** [comment]
> Correct, but even so the English translation can be fixed in Crowdin.
Yes, but I thought that it might look suspicious if I override english original file with english translation. 

Thank you once again!

**Comment by dwarfwing** [comment]
This issue can be closed.
